// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Bulgarian (`bg`).
class AppLocalizationsBg extends AppLocalizations {
  AppLocalizationsBg([String locale = 'bg']) : super(locale);

  @override
  String get appTitle => 'Каролина';

  @override
  String get home => 'Начало';

  @override
  String get analytics => 'Анализ';

  @override
  String get settings => 'Настройки';

  @override
  String get calories => 'калории';

  @override
  String get carbs => 'Въглехидрати';

  @override
  String get protein => 'Протеин';

  @override
  String get fats => 'Мазнини';

  @override
  String get setYourGoals => 'Постави си целите';

  @override
  String get autoGenerate => 'Автоматично генериране';

  @override
  String get autoGenerateDescription =>
      'Автоматично генериране на цели с помощта на експертни хранителни алгоритми';

  @override
  String get noFoodLogged => 'Няма регистрирана храна';

  @override
  String get tapPlusToTrack =>
      'Докосни + за да проследиш прогреса си и постигнеш целите си';

  @override
  String get analyzing => 'Анализиране на храна...';

  @override
  String achievedGoal(int percent) {
    return 'Постигнахте $percent% от целта си!';
  }

  @override
  String get database => 'База данни';

  @override
  String get gallery => 'Галерия';

  @override
  String get workout => 'Регистрирай тренировка';

  @override
  String get scanFood => 'Сканирай храна';

  @override
  String get log => 'Регистрирай';

  @override
  String get monday => 'Пон';

  @override
  String get tuesday => 'Вто';

  @override
  String get wednesday => 'Сря';

  @override
  String get thursday => 'Чет';

  @override
  String get friday => 'Пет';

  @override
  String get saturday => 'Съб';

  @override
  String get sunday => 'Нед';

  @override
  String get consistencyBuildsHealth => 'Постоянството изгражда здраве';

  @override
  String get healthHabitsDescription =>
      'За да постигнеш целите си и поддържаш теглото, установи рутина и създай здравословни навици. Предизвикай се и работи върху това всеки ден.';

  @override
  String get positiveHealthEffects =>
      'Скоро ще видиш положителни ефекти\nвърху здравето си';

  @override
  String get healthBenefits =>
      'Намален риск от диабет, по-ниско кръвно\nналягане, подобрени нива на холестерол';

  @override
  String get enterReferralCode => 'Въведи референтен код';

  @override
  String get notRequired => '(не е задължително)';

  @override
  String get influencerCode => 'Код на влиятел';

  @override
  String get confirm => 'Потвърди';

  @override
  String get generatingYourPlan => 'Генериране на твоя\nперсонализиран план';

  @override
  String get preparingFor => 'Подготовка за';

  @override
  String get continue_ => 'Продължи';

  @override
  String get startTrackingToday => 'Започни проследяване с\nКаролина днес.';

  @override
  String get photoYourMeal => 'ПРОСТО СНИМИ\nХРАНАТА СИ';

  @override
  String get photoYourMealDesc =>
      'Просто снимай храната си и автоматично получавай калорична информация';

  @override
  String get totalCalories => 'КОНТРОЛИРАЙ\nКАЛОРИИТЕ БЕЗ УСИЛИЕ';

  @override
  String get controlCaloriesEffortlessly =>
      'Проследи калориите без стрес и постигни целите си по-лесно от всякога';

  @override
  String get achieveGoalsFaster => 'ПОСТИГНИ ЦЕЛИТЕ ПО-БЪРЗО\nОТ ВСЯКОГА';

  @override
  String get achieveGoalsDesc =>
      'Нашата AI технология ще те води стъпка по стъпка към целите ти';

  @override
  String get notificationReminder =>
      'Ще ти напомним преди\nбезплатният ти пробен период да приключи.';

  @override
  String get freeTrialInfo =>
      'Опитай за €0.00 - Без такса, ако отмениш навреме. Отмени по всяко време.';

  @override
  String get tryForFree => 'Опитай БЕЗПЛАТНО';

  @override
  String get pricingTitle => '3 дни безплатно, след това €39.99\nна година.';

  @override
  String get day1 => 'Ден 1';

  @override
  String get day1Title => 'Отключи Каролина Про';

  @override
  String get day1Description => 'Отключи Каролина Про и разгледай всичко.';

  @override
  String get day2 => 'Ден 2';

  @override
  String get day2Title => 'Приятелско напомняне';

  @override
  String get day2Description =>
      'Получи приятелско напомняне преди пробният период да приключи.';

  @override
  String get day3 => 'Ден 3';

  @override
  String get day3Title => 'Продължи с плана';

  @override
  String get day3Description => 'Продължи с избрания план.';

  @override
  String get yearlyPlan => 'Годишен - 3-дневен безплатен пробен период';

  @override
  String get yearlyPrice => '€2.91 /месец';

  @override
  String get monthlyPlan => 'Месечен - Без безплатен пробен период';

  @override
  String get startTrialButton => 'Започни моя 3-дневен пробен период за €0.00';

  @override
  String get cancelAnytime => 'Отмени по всяко време';

  @override
  String get smarterWayTitle =>
      'Твоят по-умен начин да проследиш\nкакво ядеш започва тук';

  @override
  String get noCalorieMath => 'Няма повече калорична математика';

  @override
  String get noCalorieMathDesc =>
      'Ние правим изчисленията, ти се наслаждаваш на храната.';

  @override
  String get scanTrackDone => 'Сканирай. Проследи. Готово';

  @override
  String get scanTrackDoneDesc => 'Регистрирането на храна отнема секунди.';

  @override
  String get stayOnTopEffortlessly => 'Оставай на върха без усилие';

  @override
  String get stayOnTopEffortlesslyDesc =>
      'Нежните напомняния те поддържат постоянен.';

  @override
  String get language => 'Език';

  @override
  String get english => 'English';

  @override
  String get hrvatski => 'Hrvatski';

  @override
  String get srpski => 'Srpski';

  @override
  String get bosanski => 'Bosanski';

  @override
  String get slovenscina => 'Slovenščina';

  @override
  String get crnogorski => 'Crnogorski';

  @override
  String get makedonski => 'Македонски';

  @override
  String get bulgarski => 'Български';

  @override
  String get romana => 'Română';

  @override
  String get magyar => 'Magyar';

  @override
  String get appearance => 'Външен вид';

  @override
  String get light => 'Светло';

  @override
  String get dark => 'Тъмно';

  @override
  String get automatic => 'Автоматично';

  @override
  String get createYourAccount => 'Създай своя акаунт';

  @override
  String get welcomeBack => 'Добре дошъл отново';

  @override
  String get continueWithApple => 'Продължи с Apple';

  @override
  String get continueWithGoogle => 'Продължи с Google';

  @override
  String get wantToSignInLater => 'Искаш ли да се впишеш по-късно? ';

  @override
  String get skip => 'Пропусни';

  @override
  String get byContinuingAgree =>
      'Продължавайки, приемаш нашите\nУсловия за ползване и Политика за поверителност';

  @override
  String get haveYouCountedCalories => 'Броил ли си\nкалории преди?';

  @override
  String get triedButStopped => 'Опитах, но спрях.';

  @override
  String get neverSeemComplex => 'Никога. Изглежда сложно.';

  @override
  String get yesStillDoing => 'Да, и все още го правя.';

  @override
  String get logStreak => 'Ред на регистриране';

  @override
  String get caloriesMoreToGo => 'Още калории за постигане!';

  @override
  String get todaysLunchTotals => 'Днешни общо за обяд';

  @override
  String get mealTotals => 'Общо за хранения';

  @override
  String get consistencyMatters =>
      'Постоянството е важно за постигане на целите ти!';

  @override
  String get continueButton => 'Продължи';

  @override
  String get kalorina => 'Каролина';

  @override
  String get exercise => 'Упражнение';

  @override
  String get cardio => 'Кардио';

  @override
  String get cardioSubtitle =>
      'Регистрирай бягане, колоездене, HIIT или всякаква издръжливост';

  @override
  String get weightTraining => 'Тренировка с тежести';

  @override
  String get weightTrainingSubtitle =>
      'Проследи тренировки в фитнеса, серии и силови упражнения';

  @override
  String get describeExercise => 'Опиши упражнението';

  @override
  String get describeExerciseSubtitle => 'Нека AI изчисли изгорените калории';

  @override
  String get directInput => 'Директен Вход';

  @override
  String get directInputSubtitle => 'Въведи изгорените калории сам';

  @override
  String get food => 'Храна';

  @override
  String get myMeals => 'Моите Ястия';

  @override
  String get myMealsSubtitle =>
      'Проследи тренировки в фитнеса, серии и силови упражнения';

  @override
  String get myFoods => 'Моята Храна';

  @override
  String get myFoodsSubtitle => 'Нека AI изчисли изгорените калории';

  @override
  String get savedScans => 'Запазени Сканирания';

  @override
  String get savedScansSubtitle => 'Въведи изгорените калории сам';

  @override
  String get directInputFood => 'Директен вход';

  @override
  String get directInputFoodSubtitle => 'Въведи какво си ял сам';

  @override
  String get howDoesItWork => 'Как работи?';

  @override
  String get currentStreak => 'Текущ ред';

  @override
  String get longestStreak => 'Най-дълъг ред';

  @override
  String get day => 'ден';

  @override
  String get days => 'дни';

  @override
  String get successfulDay => 'Успешен ден';

  @override
  String get failedDay => 'Неуспешен ден';

  @override
  String get undo => 'Отмяна';

  @override
  String get error => 'Грешка';

  @override
  String get success => 'Успех';

  @override
  String get info => 'Инфо';

  @override
  String get failedToCreateStreak => 'Неуспешно създаване на ред';

  @override
  String get streakUndoneFor => 'Ред отменен за';

  @override
  String get noStreakToUndoFor => 'Няма ред за отмяна за';

  @override
  String get howDoesItWorkTitle => 'Как работи?';

  @override
  String get howDoesItWorkDescription =>
      'Всеки ден можете да регистрирате своя огън, за да размислите дали наистина сте постигнали това, което искате.';

  @override
  String get successfulDescription =>
      'Успешно → Постигнахте дневната си цел или се чувствате удовлетворени от прогреса си.';

  @override
  String get failedDescription =>
      'Неуспешно → Не постигнахте целта си или денят не мина както планирахте.';

  @override
  String get streakExplanation =>
      'Вашите огньове изграждат редове, които показват вашата последователност. Колкото по-често регистрирате честно, толкова по-ясно ще видите реалния си прогрес.';

  @override
  String get logExercise => 'Регистрирай упражнение';

  @override
  String get weightTrainingTab => 'Тренировка с тежести';

  @override
  String get describeTab => 'Опиши';

  @override
  String get directInputTab => 'Директен вход';

  @override
  String get low => 'Ниско';

  @override
  String get medium => 'Средно';

  @override
  String get high => 'Високо';

  @override
  String get intensity => 'Интензитет';

  @override
  String get duration => 'Продължителност';

  @override
  String get fifteenMin => '15 мин';

  @override
  String get thirtyMin => '30 мин';

  @override
  String get fortyFiveMin => '45 мин';

  @override
  String get sixtyMin => '60 мин';

  @override
  String get logging => 'Регистриране...';

  @override
  String get add => 'Добави';

  @override
  String get aiPowered => 'Задвижвано от ИИ';

  @override
  String get explainWorkoutPlaceholder =>
      'Обясни продължителността на тренировката, усилията и т.н.';

  @override
  String get workoutExample =>
      'Пример: \"Тренировка на горната част на тялото, 45 мин, средни усилия\"';

  @override
  String get estimating => 'Оценяване...';

  @override
  String get aiEstimate => 'ИИ оценка';

  @override
  String get whyThisEstimate => 'Защо тази оценка';

  @override
  String get typeCaloriesBurned => 'Въведи изгорените калории сам';

  @override
  String get zeroPlaceholder => '0';

  @override
  String get nearSprintingDescription =>
      'Почти спринт, трудно да се поддържа дълго';

  @override
  String get steadyRunDescription => 'Стабилен бяг, поносимо усилие';

  @override
  String get briskWalkDescription => 'Бърза ходба, удобно дишане';

  @override
  String get heavyWeightsDescription =>
      'Тежки тежести, близо до максимално усилие';

  @override
  String get moderateWeightsDescription => 'Умерени тежести, потене';

  @override
  String get lightWeightsDescription => 'Леки тежести, без потене';

  @override
  String get logFood => 'Регистрирай Храна';

  @override
  String get all => 'Всички';

  @override
  String get searchMeals => 'Търси ястия...';

  @override
  String get searchFoods => 'Търси храна...';

  @override
  String get searchScannedMeals => 'Търси сканирани ястия...';

  @override
  String get chickenBr => 'Пиле br';

  @override
  String get suggestions => 'Предложения';

  @override
  String get noSuggestionsAvailable => 'Няма налични предложения';

  @override
  String get noMealsSavedYet => 'Все още няма запазени ястия';

  @override
  String get noFoodsCreatedYet => 'Все още не са създадени храни';

  @override
  String get createFood => 'Създай Храна';

  @override
  String get yourSavedScansWillAppearHere =>
      'Вашите запазени сканирания ще се появят тук';

  @override
  String get savedScansContentComingSoon =>
      'Съдържанието на запазените сканирания скоро';

  @override
  String get editName => 'Редактирай Име';

  @override
  String get caloriesLabel => 'Калории';

  @override
  String get caloriesPlaceholder => '512';

  @override
  String get ingredients => 'Съставки';

  @override
  String get addMore => 'Добави Повече';

  @override
  String get amount => 'Количество';

  @override
  String get saveFood => 'Запази Храна';

  @override
  String get createAMeal => 'Създай Ястие';

  @override
  String get enterAmount => 'Въведи Количество';

  @override
  String get enterAmountPlaceholder => 'Въведи количество';

  @override
  String get cancel => 'Отказ';

  @override
  String get save => 'Запази';

  @override
  String get name => 'Име *';

  @override
  String get enterIngredientName => 'Въведи име на съставката';

  @override
  String get quantityUnit => 'Количество и Мерна Единица';

  @override
  String get amountPlaceholder => 'Количество';

  @override
  String get unitPlaceholder => 'Мерна единица (г, чаша, супена лъжица)';

  @override
  String get nutritionOptional => 'Хранителни вещества (По избор)';

  @override
  String get caloriesPlaceholder2 => 'Калории';

  @override
  String get proteinG => 'Протеин (г)';

  @override
  String get carbsG => 'Въглехидрати (г)';

  @override
  String get fatG => 'Мазнини (г)';

  @override
  String get editIngredient => 'Редактирай Съставка';

  @override
  String get addIngredient => 'Добави Съставка';

  @override
  String get scannedMeal => 'Сканирано Ястие';

  @override
  String get setName => 'Задай Име';

  @override
  String get personalInformation => 'Лична Информация';

  @override
  String get weight => 'Тегло';

  @override
  String get height => 'Височина';

  @override
  String get age => 'Възраст';

  @override
  String get gender => 'Пол';

  @override
  String get dailyStepsGoal => 'Дневна цел за стъпки';

  @override
  String get addBurnedCaloriesToGoal => 'Добави Изгорени Калории към Целта';

  @override
  String get account => 'Акаунт';

  @override
  String get manageYourProfileAndAccountSettings =>
      'Управлявай профила и настройките на акаунта си';

  @override
  String get healthTracking => 'Проследяване на Здравето';

  @override
  String get viewYourHealthConsistencyAndProgress =>
      'Виж здравословната си последователност и напредък';

  @override
  String get notifications => 'Известия';

  @override
  String get configureYourNotificationPreferences =>
      'Конфигурирай предпочитанията си за известия';

  @override
  String get about => 'За Приложението';

  @override
  String get appVersionAndInformation => 'Версия на приложението и информация';

  @override
  String get enterYourName => 'Въведи името си';

  @override
  String get selectGender => 'Избери Пол';

  @override
  String get male => 'Мъж';

  @override
  String get female => 'Жена';

  @override
  String get years => 'години';

  @override
  String get steps => 'стъпки';

  @override
  String get progress => 'Напредък';

  @override
  String get myWeight => 'Моето Тегло';

  @override
  String get logWeight => 'Запиши Тегло';

  @override
  String get targetWeight => 'Целево Тегло';

  @override
  String get update => 'Актуализирай';

  @override
  String get toTargetWeight => 'До целевото тегло';

  @override
  String get weightGoalProgress => 'Напредък на Целевото Тегло';

  @override
  String get thirtyDays => '30 Дни';

  @override
  String get ninetyDays => '90 Дни';

  @override
  String get sixMonths => '6 Месеца';

  @override
  String get oneYear => '1 Година';

  @override
  String get allTime => 'Цялото Време';

  @override
  String get start => 'Начало';

  @override
  String get now => 'Сега';

  @override
  String get avgDailyProgress => 'Среден дневен напредък';

  @override
  String get avgDailyLost => 'Средно дневно загубено';

  @override
  String get avgDailyGained => 'Средно дневно спечелено';

  @override
  String get addProgressPhoto => 'Добави Фотография на Напредъка';

  @override
  String get camera => 'Камера';

  @override
  String get progressPhotos => 'Фотографии на Напредъка';

  @override
  String get seeProgress => 'Виж напредъка';

  @override
  String get uploadPhoto => 'Качи Фотография';

  @override
  String get upload => 'Качи';

  @override
  String get stepsToday => 'Стъпки Днес';

  @override
  String get tapToEnableHealthPermissions =>
      'Докоснете за активиране на здравни разрешения';

  @override
  String get addBurnedCaloriesToDailyGoal =>
      'Добави изгорени калории към дневната цел';

  @override
  String get caloriesBurned => 'Изгорени Калории';

  @override
  String get kg => 'кг';

  @override
  String get sinceLastWeighIn => 'от последното измерване';

  @override
  String get kgPerDay => 'кг/ден';

  @override
  String get kgToGo => 'кг до цел';

  @override
  String get greatJob => 'Отлично';

  @override
  String get youGained => 'Спечелихте';

  @override
  String get weighInDue => 'Измерване необходимо';

  @override
  String nextWeighIn(Object days) {
    return 'Следно измерване: $daysд';
  }

  @override
  String get enterUsername => 'Въведете потребителско име';

  @override
  String get birthday => 'Рожден ден';

  @override
  String get personalDetails => 'Лични данни';

  @override
  String get rolloverLeftOverCalories =>
      'Прехвърли до 200 останали калории от вчера';

  @override
  String get addBurnedCalories => 'Добави изгорени калории';

  @override
  String get inviteFriends => 'Покани приятели';

  @override
  String get adjustMacronutrients => 'Настрой макронутриенти';

  @override
  String get support => 'Поддръжка';

  @override
  String get privacyPolicy => 'Политика за поверителност';

  @override
  String get termsAndConditions => 'Условия и положения';

  @override
  String get deleteAccount => 'Изтрий акаунт';

  @override
  String get logout => 'Изход';

  @override
  String get deleteAccountTitle => 'Изтрий акаунт?';

  @override
  String get accountWillBePermanentlyDeleted =>
      'Акаунтът ще бъде изтрит завинаги';

  @override
  String get logoutTitle => 'Изход?';

  @override
  String get areYouSureYouWantToLogOut =>
      'Сигурни ли сте, че искате да излезете?';

  @override
  String get recentlyUploaded => 'Наскоро качено';

  @override
  String get cannotLogFutureStreak => 'Не може да се записват бъдещи дати';

  @override
  String get cannotLogFutureStreakDescription =>
      'Можете да записвате серии само за днес и минали дати. Бъдещите дати ще се отключат, когато настъпят!';

  @override
  String get ok => 'Добре';
}
