// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Italian (`it`).
class AppLocalizationsIt extends AppLocalizations {
  AppLocalizationsIt([String locale = 'it']) : super(locale);

  @override
  String get appTitle => 'Karolina';

  @override
  String get home => 'Home';

  @override
  String get analytics => 'Analisi';

  @override
  String get settings => 'Impostazioni';

  @override
  String get calories => 'calorie';

  @override
  String get carbs => 'Carboidrati';

  @override
  String get protein => 'Proteine';

  @override
  String get fats => 'Grassi';

  @override
  String get setYourGoals => 'Imposta I Tuoi Obiettivi';

  @override
  String get autoGenerate => 'Generazione Automatica';

  @override
  String get autoGenerateDescription =>
      'Genera automaticamente obiettivi utilizzando algoritmi nutrizionali esperti';

  @override
  String get noFoodLogged => 'Nessun cibo registrato';

  @override
  String get tapPlusToTrack =>
      'Tocca + per monitorare i tuoi progressi e raggiungere i tuoi obiettivi';

  @override
  String get analyzing => 'Analizzando cibo...';

  @override
  String achievedGoal(int percent) {
    return 'Hai raggiunto il $percent% del tuo obiettivo!';
  }

  @override
  String get database => 'Database';

  @override
  String get gallery => 'Galleria';

  @override
  String get workout => 'Registra Allenamento';

  @override
  String get scanFood => 'Scansiona Cibo';

  @override
  String get log => 'Registro';

  @override
  String get monday => 'Lun';

  @override
  String get tuesday => 'Mar';

  @override
  String get wednesday => 'Mer';

  @override
  String get thursday => 'Gio';

  @override
  String get friday => 'Ven';

  @override
  String get saturday => 'Sab';

  @override
  String get sunday => 'Dom';

  @override
  String get consistencyBuildsHealth => 'La costanza costruisce la salute';

  @override
  String get healthHabitsDescription =>
      'Per raggiungere i tuoi obiettivi e mantenere il peso, stabilisci una routine e crea abitudini sane. Sfidati e lavora su questo ogni giorno.';

  @override
  String get positiveHealthEffects =>
      'Vedrai effetti positivi\nsulla tua salute presto';

  @override
  String get healthBenefits =>
      'Rischio ridotto di diabete, pressione sanguigna\npiù bassa, livelli di colesterolo migliorati';

  @override
  String get enterReferralCode => 'Inserisci codice di riferimento';

  @override
  String get notRequired => '(non richiesto)';

  @override
  String get influencerCode => 'Codice Influencer';

  @override
  String get confirm => 'Conferma';

  @override
  String get generateYourPlan => 'Genera il tuo piano';

  @override
  String get generatingYourPlan => 'Generando il tuo\npiano personalizzato';

  @override
  String get preparingFor => 'Preparazione per';

  @override
  String get continue_ => 'Continua';

  @override
  String get startTrackingToday => 'Inizia a tracciare con\nKalorina oggi.';

  @override
  String get photoYourMeal => 'FOTOGRAFA SEMPLICEMENTE\nIL TUO PASTO';

  @override
  String get photoYourMealDesc =>
      'Scatta semplicemente una foto del tuo pasto e ottieni automaticamente informazioni caloriche';

  @override
  String get totalCalories => 'CONTROLLA LE\nCALORIE SENZA SFORZO';

  @override
  String get controlCaloriesEffortlessly =>
      'Traccia le calorie senza stress e raggiungi i tuoi obiettivi più facilmente che mai';

  @override
  String get achieveGoalsFaster =>
      'RAGGIUNGI GLI OBIETTIVI PIÙ VELOCEMENTE\nCHE MAI';

  @override
  String get achieveGoalsDesc =>
      'La nostra tecnologia AI ti guiderà passo dopo passo verso i tuoi obiettivi';

  @override
  String get notificationReminder =>
      'Ti ricorderemo prima che\nla tua prova gratuita finisca.';

  @override
  String get freeTrialInfo =>
      'Prova per €0.00 - Nessun addebito se annulli in\ntempo. Annulla in qualsiasi momento.';

  @override
  String get tryForFree => 'Prova GRATIS';

  @override
  String get pricingTitle => '3 days free, then €39.99\nper year.';

  @override
  String get day1 => 'Day 1';

  @override
  String get day1Title => 'Unlock Kalorina Pro';

  @override
  String get day1Description => 'Unlock Kalorina Pro and explore everything.';

  @override
  String get day2 => 'Day 2';

  @override
  String get day2Title => 'Friendly Reminder';

  @override
  String get day2Description =>
      'Get a friendly reminder before your trial ends.';

  @override
  String get day3 => 'Day 3';

  @override
  String get day3Title => 'Continue with Plan';

  @override
  String get day3Description => 'Continue with your chosen plan.';

  @override
  String get yearlyPlan => 'Yearly - 3 Day Free Trial';

  @override
  String get yearlyPrice => '€2.91 /mo';

  @override
  String get monthlyPlan => 'Monthly - No Free Trial';

  @override
  String get startTrialButton => 'Start My 3-Day Trial For €0.00';

  @override
  String get cancelAnytime => 'Cancel at any time';

  @override
  String get smarterWayTitle =>
      'Your smarter way to track\nwhat you eat starts here';

  @override
  String get noCalorieMath => 'No more calorie math';

  @override
  String get noCalorieMathDesc => 'We do the numbers, you enjoy the food.';

  @override
  String get scanTrackDone => 'Scan. Track. Done';

  @override
  String get scanTrackDoneDesc => 'Logging food takes seconds.';

  @override
  String get stayOnTopEffortlessly => 'Stay on top effortlessly';

  @override
  String get stayOnTopEffortlesslyDesc =>
      'Gentle reminders keep you consistent.';

  @override
  String get language => 'Lingua';

  @override
  String get english => 'English';

  @override
  String get hrvatski => 'Hrvatski';

  @override
  String get srpski => 'Srpski';

  @override
  String get bosanski => 'Bosanski';

  @override
  String get slovenscina => 'Slovenščina';

  @override
  String get crnogorski => 'Crnogorski';

  @override
  String get makedonski => 'Македонски';

  @override
  String get bulgarski => 'Български';

  @override
  String get romana => 'Română';

  @override
  String get magyar => 'Magyar';

  @override
  String get appearance => 'Appearance';

  @override
  String get light => 'Light';

  @override
  String get dark => 'Dark';

  @override
  String get automatic => 'Automatic';

  @override
  String get createYourAccount => 'Crea il tuo account';

  @override
  String get welcomeBack => 'Bentornato';

  @override
  String get continueWithApple => 'Continua con Apple';

  @override
  String get continueWithGoogle => 'Continua con Google';

  @override
  String get creatingAccount => 'Creazione account...';

  @override
  String get wantToSignInLater => 'Vuoi accedere più tardi? ';

  @override
  String get skip => 'Salta';

  @override
  String get byContinuingAgree =>
      'Continuando accetti i nostri\nTermini di servizio e Informativa sulla privacy';

  @override
  String get haveYouCountedCalories => 'Have you counted\ncalories before?';

  @override
  String get triedButStopped => 'I\'ve tried but stopped.';

  @override
  String get neverSeemComplex => 'Never. It seems complex.';

  @override
  String get yesStillDoing => 'Yes, and I\'m still doing it.';

  @override
  String get logStreak => 'Log Streak';

  @override
  String get caloriesMoreToGo => 'Calories more to go!';

  @override
  String get todaysLunchTotals => 'Today\'s lunch totals';

  @override
  String get mealTotals => 'Meal totals';

  @override
  String get consistencyMatters =>
      'Consistency matters for achieving your goals!';

  @override
  String get continueButton => 'Continue';

  @override
  String get kalorina => 'Kalorina';

  @override
  String get exercise => 'Esercizio';

  @override
  String get cardio => 'Cardio';

  @override
  String get cardioSubtitle =>
      'Registra corse, ciclismo, HIIT o qualsiasi attività di resistenza';

  @override
  String get weightTraining => 'Allenamento con i Pesi';

  @override
  String get weightTrainingSubtitle =>
      'Traccia sessioni in palestra, serie ed esercizi di forza';

  @override
  String get describeExercise => 'Descrivi Esercizio';

  @override
  String get describeExerciseSubtitle =>
      'Lascia che l\'IA calcoli le calorie bruciate';

  @override
  String get directInput => 'Inserimento Diretto';

  @override
  String get directInputSubtitle => 'Digita le calorie bruciate tu stesso';

  @override
  String get food => 'Cibo';

  @override
  String get myMeals => 'I Miei Pasti';

  @override
  String get myMealsSubtitle =>
      'Traccia sessioni in palestra, serie ed esercizi di forza';

  @override
  String get myFoods => 'I Miei Cibi';

  @override
  String get myFoodsSubtitle => 'Lascia che l\'IA calcoli le calorie bruciate';

  @override
  String get savedScans => 'Scansioni Salvate';

  @override
  String get savedScansSubtitle => 'Digita le calorie bruciate tu stesso';

  @override
  String get directInputFood => 'Input Diretto';

  @override
  String get directInputFoodSubtitle =>
      'Digita quello che hai mangiato tu stesso';

  @override
  String get howDoesItWork => 'How does it work?';

  @override
  String get currentStreak => 'Current streak';

  @override
  String get longestStreak => 'Longest streak';

  @override
  String get day => 'day';

  @override
  String get days => 'days';

  @override
  String get successfulDay => 'Successful day';

  @override
  String get failedDay => 'Failed day';

  @override
  String get undo => 'Undo';

  @override
  String get error => 'Error';

  @override
  String get success => 'Success';

  @override
  String get info => 'Info';

  @override
  String get failedToCreateStreak => 'Failed to create streak';

  @override
  String get streakUndoneFor => 'Streak undone for';

  @override
  String get noStreakToUndoFor => 'No streak to undo for';

  @override
  String get howDoesItWorkTitle => 'How does it work?';

  @override
  String get howDoesItWorkDescription =>
      'Every day, you can log your fire to reflect on whether you felt like you truly achieved what you wanted.';

  @override
  String get successfulDescription =>
      'Successful → You reached your daily goal or feel satisfied with your progress.';

  @override
  String get failedDescription =>
      'Failed → You didn\'t meet your goal or the day didn\'t go as planned.';

  @override
  String get streakExplanation =>
      'Your fires build streaks that show your consistency. The longer you log honestly, the clearer you\'ll see your real progress.';

  @override
  String get logExercise => 'Log Exercise';

  @override
  String get weightTrainingTab => 'Weight Training';

  @override
  String get describeTab => 'Describe';

  @override
  String get directInputTab => 'Direct Input';

  @override
  String get low => 'Low';

  @override
  String get medium => 'Medium';

  @override
  String get high => 'High';

  @override
  String get intensity => 'Intensity';

  @override
  String get duration => 'Duration';

  @override
  String get fifteenMin => '15 min';

  @override
  String get thirtyMin => '30 min';

  @override
  String get fortyFiveMin => '45 min';

  @override
  String get sixtyMin => '60 min';

  @override
  String get logging => 'Logging...';

  @override
  String get add => 'Aggiungi';

  @override
  String get aiPowered => 'AI Powered';

  @override
  String get explainWorkoutPlaceholder =>
      'Explain workout duration, effort, etc.';

  @override
  String get workoutExample =>
      'Example: \"Upper body session, 45 mins, medium effort\"';

  @override
  String get estimating => 'Estimating...';

  @override
  String get aiEstimate => 'AI Estimate';

  @override
  String get whyThisEstimate => 'Why this estimate';

  @override
  String get typeCaloriesBurned => 'Digita le calorie bruciate tu stesso';

  @override
  String get zeroPlaceholder => '0';

  @override
  String get nearSprintingDescription =>
      'Quasi sprint, difficile da sostenere a lungo';

  @override
  String get steadyRunDescription => 'Corsa costante, sforzo gestibile';

  @override
  String get briskWalkDescription =>
      'Camminata veloce, respirazione confortevole';

  @override
  String get heavyWeightsDescription =>
      'Pesi pesanti, vicino allo sforzo massimo';

  @override
  String get moderateWeightsDescription => 'Pesi moderati, sudando';

  @override
  String get lightWeightsDescription => 'Pesi leggeri, senza sudare';

  @override
  String get logFood => 'Registra Cibo';

  @override
  String get all => 'Tutto';

  @override
  String get search => 'Search';

  @override
  String get searchMeals => 'Cerca pasti...';

  @override
  String get searchFoods => 'Cerca cibi...';

  @override
  String get searchScannedMeals => 'Cerca pasti scansionati...';

  @override
  String get chickenBr => 'Pollo br';

  @override
  String get suggestions => 'Suggerimenti';

  @override
  String get noSuggestionsAvailable => 'Nessun suggerimento disponibile';

  @override
  String get noMealsSavedYet => 'Nessun pasto salvato ancora';

  @override
  String get noFoodsCreatedYet => 'Nessun cibo creato ancora';

  @override
  String get createFood => 'Crea Cibo';

  @override
  String get yourSavedScansWillAppearHere =>
      'Le tue scansioni salvate appariranno qui';

  @override
  String get savedScansContentComingSoon =>
      'Contenuto delle scansioni salvate presto';

  @override
  String get editName => 'Modifica Nome';

  @override
  String get caloriesLabel => 'Calorie';

  @override
  String get caloriesPlaceholder => '512';

  @override
  String get ingredients => 'Ingredienti';

  @override
  String get addMore => 'Aggiungi Altro';

  @override
  String get amount => 'Quantità';

  @override
  String get saveFood => 'Salva Cibo';

  @override
  String get createAMeal => 'Crea un Pasto';

  @override
  String get enterAmount => 'Inserisci Quantità';

  @override
  String get enterAmountPlaceholder => 'Inserisci quantità';

  @override
  String get cancel => 'Annulla';

  @override
  String get save => 'Salva';

  @override
  String get name => 'Nome *';

  @override
  String get enterIngredientName => 'Inserisci nome ingrediente';

  @override
  String get quantityUnit => 'Quantità e Unità';

  @override
  String get amountPlaceholder => 'Quantità';

  @override
  String get unitPlaceholder => 'Unità (g, tazza, cucchiaio)';

  @override
  String get nutritionOptional => 'Nutrizione (Opzionale)';

  @override
  String get caloriesPlaceholder2 => 'Calorie';

  @override
  String get proteinG => 'Proteine (g)';

  @override
  String get carbsG => 'Carboidrati (g)';

  @override
  String get fatG => 'Grassi (g)';

  @override
  String get editIngredient => 'Modifica Ingrediente';

  @override
  String get addIngredient => 'Aggiungi Ingrediente';

  @override
  String get scannedMeal => 'Pasto Scansionato';

  @override
  String get setName => 'Imposta Nome';

  @override
  String get personalInformation => 'Informazioni Personali';

  @override
  String get weight => 'Peso';

  @override
  String get height => 'Altezza';

  @override
  String get age => 'Età';

  @override
  String get gender => 'Genere';

  @override
  String get dailyStepsGoal => 'Obiettivo giornaliero di passi';

  @override
  String get addBurnedCaloriesToGoal =>
      'Aggiungi Calorie Bruciate all\'Obiettivo';

  @override
  String get account => 'Account';

  @override
  String get manageYourProfileAndAccountSettings =>
      'Gestisci il tuo profilo e le impostazioni dell\'account';

  @override
  String get healthTracking => 'Monitoraggio Salute';

  @override
  String get viewYourHealthConsistencyAndProgress =>
      'Vedi la tua coerenza di salute e progressi';

  @override
  String get notifications => 'Notifiche';

  @override
  String get configureYourNotificationPreferences =>
      'Configura le tue preferenze di notifica';

  @override
  String get about => 'Informazioni';

  @override
  String get appVersionAndInformation => 'Versione dell\'app e informazioni';

  @override
  String get enterYourName => 'Inserisci il tuo nome';

  @override
  String get selectGender => 'Seleziona Genere';

  @override
  String get male => 'Maschio';

  @override
  String get female => 'Femmina';

  @override
  String get years => 'anni';

  @override
  String get steps => 'passi';

  @override
  String get progress => 'Progresso';

  @override
  String get myWeight => 'Il Mio Peso';

  @override
  String get logWeight => 'Registra Peso';

  @override
  String get targetWeight => 'Peso Obiettivo';

  @override
  String get update => 'Aggiorna';

  @override
  String get toTargetWeight => 'Verso il peso obiettivo';

  @override
  String get weightGoalProgress => 'Progresso Peso Obiettivo';

  @override
  String get thirtyDays => '30 Giorni';

  @override
  String get ninetyDays => '90 Giorni';

  @override
  String get sixMonths => '6 Mesi';

  @override
  String get oneYear => '1 Anno';

  @override
  String get allTime => 'Tutto il Tempo';

  @override
  String get start => 'Inizio';

  @override
  String get now => 'Ora';

  @override
  String get avgDailyProgress => 'Progresso giornaliero medio';

  @override
  String get avgDailyLost => 'Perso giornalmente in media';

  @override
  String get avgDailyGained => 'Guadagnato giornalmente in media';

  @override
  String get addProgressPhoto => 'Aggiungi Foto Progresso';

  @override
  String get camera => 'Fotocamera';

  @override
  String get selectImageSource => 'Select Image Source';

  @override
  String get progressPhotos => 'Foto Progresso';

  @override
  String get seeProgress => 'Vedi progresso';

  @override
  String get uploadPhoto => 'Carica Foto';

  @override
  String get upload => 'Carica';

  @override
  String get stepsToday => 'Passi Oggi';

  @override
  String get tapToEnableHealthPermissions =>
      'Tocca per abilitare i permessi di salute';

  @override
  String get addBurnedCaloriesToDailyGoal =>
      'Aggiungi calorie bruciate all\'obiettivo giornaliero';

  @override
  String get caloriesBurned => 'Calorie Bruciate';

  @override
  String get kg => 'kg';

  @override
  String get sinceLastWeighIn => 'dall\'ultima pesata';

  @override
  String get kgPerDay => 'kg/giorno';

  @override
  String get kgToGo => 'kg da raggiungere';

  @override
  String get greatJob => 'Ottimo';

  @override
  String get youGained => 'Hai guadagnato';

  @override
  String get weighInDue => 'Pesata dovuta';

  @override
  String nextWeighIn(Object days) {
    return 'Prossima pesata: ${days}g';
  }

  @override
  String get enterUsername => 'Inserisci nome utente';

  @override
  String get birthday => 'Compleanno';

  @override
  String get personalDetails => 'Dettagli personali';

  @override
  String get rolloverLeftOverCalories =>
      'Trasferisci fino a 200 calorie rimanenti di ieri';

  @override
  String get addBurnedCalories => 'Aggiungi calorie bruciate';

  @override
  String get inviteFriends => 'Invita amici';

  @override
  String get adjustMacronutrients => 'Regola macronutrienti';

  @override
  String get support => 'Supporto';

  @override
  String get privacyPolicy => 'Politica sulla privacy';

  @override
  String get termsAndConditions => 'Termini e condizioni';

  @override
  String get deleteAccount => 'Elimina account';

  @override
  String get logout => 'Disconnetti';

  @override
  String get deleteAccountTitle => 'Eliminare l\'account?';

  @override
  String get accountWillBePermanentlyDeleted =>
      'L\'account sarà eliminato permanentemente';

  @override
  String get logoutTitle => 'Disconnettersi?';

  @override
  String get areYouSureYouWantToLogOut =>
      'Sei sicuro di volerti disconnettere?';

  @override
  String get recentlyUploaded => 'Caricato di recente';

  @override
  String get recentlyLogged => 'Recently Logged';

  @override
  String get cannotLogFutureStreak => 'Impossibile registrare date future';

  @override
  String get cannotLogFutureStreakDescription =>
      'Puoi registrare serie solo per oggi e date passate. Le date future si sbloccheranno quando arriveranno!';

  @override
  String dayStreak(int count) {
    return 'Giorno $count Serie';
  }

  @override
  String get keepGoing => 'Continua!';

  @override
  String get ok => 'OK';

  @override
  String get whatWouldYouLikeToAchieve => 'Cosa vorresti raggiungere?';

  @override
  String get stayMotivatedAndDisciplined => 'Rimani motivato e disciplinato';

  @override
  String get feelBetterAboutYourBody =>
      'Sentirsi meglio riguardo al proprio corpo';

  @override
  String get improveHealthLongTerm => 'Migliorare la salute a lungo termine';

  @override
  String get increaseMoodAndEnergy => 'Aumentare l\'umore e l\'energia';

  @override
  String get youHaveGreatPotential =>
      'Hai un grande potenziale per raggiungere il tuo obiettivo';

  @override
  String get yourJourneyToBetterHealth =>
      'Il tuo viaggio verso una salute migliore inizia ora';

  @override
  String get youTookFirstStepToHealthier =>
      'Hai fatto il primo passo verso una versione più sana di te';

  @override
  String get trackYourFoodAndExercise => 'Traccia il tuo cibo e l\'esercizio';

  @override
  String get focusOnNutrientDenseFoods =>
      'Concentrati su cibi ricchi di nutrienti';

  @override
  String get maintainYourHealthyHabits => 'Mantieni le tue abitudini sane';

  @override
  String get balanceCarbsProteinAndFats =>
      'Bilancia carboidrati, proteine e grassi';

  @override
  String get stickToYourPersonalizedPlan =>
      'Attieniti al tuo piano personalizzato';

  @override
  String get focusOnWholeUnprocessedFoods =>
      'Concentrati su cibi integrali e non trasformati';

  @override
  String get followYourPersonalizedMealPlan =>
      'Segui il tuo piano pasti personalizzato';

  @override
  String get focusOnPortionControlAndNutrition =>
      'Concentrati sul controllo delle porzioni e sulla nutrizione';

  @override
  String get followYourPersonalizedPlan => 'Segui il tuo piano personalizzato';

  @override
  String get stayConsistentSeeRealResults =>
      'Rimani costante, vedi risultati reali';

  @override
  String get enableNotificationsForBetterResults =>
      'Abilita le notifiche per risultati migliori';

  @override
  String get recommended => '(Consigliato)';

  @override
  String get kalorinaHelpsYouKeepTrack =>
      'Kalorina ti aiuta a tenere traccia — Ricevi promemoria giornalieri';

  @override
  String get dontAllow => 'Non consentire';

  @override
  String get allow => 'Consenti';

  @override
  String get countBurnedCaloriesTowardsGoal =>
      'Contare le calorie bruciate verso l\'obiettivo giornaliero?';

  @override
  String get todaysGoal => 'Obiettivo di oggi:';

  @override
  String get stepsLabel => 'Passi:';

  @override
  String get transferExtraCaloriesToNextDay =>
      'Trasferire le calorie extra al giorno successivo?';

  @override
  String get yesterday => 'Ieri';

  @override
  String get today => 'Oggi';

  @override
  String get caloriesLeft => 'Calorie Rimanenti';

  @override
  String get everydayLogFireReflect =>
      'Ogni giorno, puoi registrare il tuo 🔥 per riflettere se hai veramente raggiunto ciò che volevi. I tuoi fuochi costruiscono serie che mostrano la tua coerenza.';

  @override
  String get longLastingHealthEffects =>
      'Vedrai effetti duraturi sulla tua salute';

  @override
  String get ninetyPercent => '90%';

  @override
  String get usersStayConsistentMaintainWeight =>
      ' degli utenti che rimangono coerenti mantengono il loro peso anche ';

  @override
  String get twelveMonthsLater => '12 mesi dopo';

  @override
  String get leaveUsReview => 'Lasciaci una recensione';

  @override
  String get joinOver10000People =>
      'Unisciti a oltre 10.000\npersone proprio come te';

  @override
  String get applied => 'Applicato';

  @override
  String get howItWorksUniqueApproach =>
      'Come funziona l\'approccio\nunico di Kalorina';

  @override
  String get scan => 'Scansiona';

  @override
  String get analyze => 'Analizza';

  @override
  String get track => 'Traccia';

  @override
  String get heightAndWeight => 'Altezza e peso';

  @override
  String get heightWeightSubtitle =>
      'Questa informazione ci aiuta a personalizzare i tuoi obiettivi calorici e nutrizionali giornalieri.';

  @override
  String get imperial => 'Imperiale';

  @override
  String get metric => 'Metrico';

  @override
  String get heightLabel => 'Altezza';

  @override
  String get weightLabel => 'Peso';

  @override
  String get whenWereYouBorn => 'Quando sei nato?';

  @override
  String get birthDateSubtitle =>
      'Questo verrà preso in considerazione nel calcolo dei tuoi obiettivi nutrizionali giornalieri.';

  @override
  String get monthLabel => 'Mese';

  @override
  String get dayLabel => 'Giorno';

  @override
  String get yearLabel => 'Anno';

  @override
  String get january => 'Gennaio';

  @override
  String get february => 'Febbraio';

  @override
  String get march => 'Marzo';

  @override
  String get april => 'Aprile';

  @override
  String get may => 'Maggio';

  @override
  String get june => 'Giugno';

  @override
  String get july => 'Luglio';

  @override
  String get august => 'Agosto';

  @override
  String get september => 'Settembre';

  @override
  String get october => 'Ottobre';

  @override
  String get november => 'Novembre';

  @override
  String get december => 'Dicembre';

  @override
  String get selectYourGender => 'Seleziona il tuo Genere';

  @override
  String get genderSelectionInfo =>
      'Seleziona il genere che corrisponde alla fisiologia del tuo corpo per un monitoraggio accurato delle calorie';

  @override
  String get maleGender => 'Uomo';

  @override
  String get femaleGender => 'Donna';

  @override
  String get howManyWorkoutsPerWeek => 'Quanti allenamenti fai a settimana';

  @override
  String get selectBestOption => 'Seleziona l\'opzione più adatta a te';

  @override
  String get noWorkouts => 'Non mi alleno';

  @override
  String get occasionalWorkouts => 'Allenamenti occasionali';

  @override
  String get severalWorkoutsWeekly => 'Diversi allenamenti settimanali';

  @override
  String get dedicatedAthlete => 'Atleta dedicato';

  @override
  String get whereDidYouHearAboutUs => 'Dove hai sentito parlare di noi?';

  @override
  String get googlePlay => 'Google Play';

  @override
  String get youtube => 'YouTube';

  @override
  String get tiktok => 'TikTok';

  @override
  String get instagram => 'Instagram';

  @override
  String get influencer => 'Influencer';

  @override
  String get friendsOrFamily => 'Amici o Famiglia';

  @override
  String get other => 'Altro';

  @override
  String get wellDoneBigStep => 'Ben fatto! Hai appena fatto\nun grande passo.';

  @override
  String get calorieTrackingPart1 =>
      'Sapevi che il conteggio delle calorie è un ';

  @override
  String get scientificallyProvenMethod => 'metodo scientificamente provato';

  @override
  String get calorieTrackingPart2 =>
      ' per raggiungere i tuoi obiettivi – e anche fino a ';

  @override
  String get twiceFaster => 'due volte più velocemente';

  @override
  String get calorieTrackingPart3 => '?';

  @override
  String get yourProgress => 'Il tuo progresso';

  @override
  String get withKalorina => 'Con Kalorina';

  @override
  String get withoutKalorina => 'Senza Kalorina';

  @override
  String get twiceMultiplier => '+2x';

  @override
  String get whatIsYourGoal => 'Qual è il tuo obiettivo';

  @override
  String get selectGoalThatSuitsYou => 'Seleziona l\'obiettivo più adatto a te';

  @override
  String get loseWeight => 'Perdere Peso';

  @override
  String get maintainWeight => 'Mantenere il Peso';

  @override
  String get gainWeight => 'Aumentare di Peso';

  @override
  String get howMuchWeightToLose => 'Quanto peso vuoi perdere?';

  @override
  String get howMuchWeightToGain => 'Quanto peso vuoi guadagnare?';

  @override
  String get whatIsDesiredWeight => 'Qual è il tuo peso desiderato?';

  @override
  String get isRealisticGoal => 'è un obiettivo realistico.';

  @override
  String get youHaveGreatPotentialLose =>
      'Hai un grande potenziale per raggiungere il tuo obiettivo!\nFacciamolo insieme!';

  @override
  String get youHaveGreatPotentialGain =>
      'Costruire muscoli richiede dedizione!\nSiamo qui per supportare il tuo viaggio!';

  @override
  String get youveGotThis => 'Ce la puoi fare!';

  @override
  String get stayStrong => 'Rimani forte!';

  @override
  String get nineOutOfTenUsers =>
      '9 utenti su 10 dicono di\nvedere risultati nella prima settimana\ndi utilizzo di Kalorina';

  @override
  String get pickWeightLossSpeed => 'Scegli la velocità di perdita di peso';

  @override
  String get pickWeightGainSpeed => 'Scegli la velocità di aumento di peso';

  @override
  String get theSafestOption => 'L\'opzione più sicura';

  @override
  String get balancedApproach => 'Approccio equilibrato';

  @override
  String get aggressivePlan => 'Piano aggressivo';

  @override
  String get doYouFollowDiet => 'Segui una dieta specifica?';

  @override
  String get helpTrackCaloriesDiet =>
      'Ti aiuteremo a tenere traccia delle calorie secondo la tua dieta';

  @override
  String get classic => 'Classica';

  @override
  String get carnivore => 'Carnivora';

  @override
  String get keto => 'Keto';

  @override
  String get vegan => 'Vegana';

  @override
  String get vegetarian => 'Vegetariana';

  @override
  String get wereHereForYou => 'Siamo qui per te!';

  @override
  String get journeySupportMessage =>
      'Il viaggio verso il tuo obiettivo può essere impegnativo a volte, ma siamo qui per supportarti ad ogni passo. Non dovrai affrontarlo da solo.';

  @override
  String get starsAcrossApps => 'Stelle Su Applicazioni';

  @override
  String get testimonial1Name => 'Giacomo L.';

  @override
  String get testimonial1Review =>
      'Non avrei mai pensato che tracciare le calorie potesse essere così facile. Ho perso 7 kg in meno di 2 mesi.';

  @override
  String get testimonial2Name => 'Sara M.';

  @override
  String get testimonial2Review =>
      'La precisione è incredibile. Finalmente so esattamente cosa sto mangiando e mi sento molto meglio.';

  @override
  String get testimonial3Name => 'Michele R.';

  @override
  String get testimonial3Review =>
      'Perfetto per la mia routine quotidiana. Scannerizzo i miei pasti rapidamente e sento progressi in una settimana.';

  @override
  String get testimonial4Name => 'Emma K.';

  @override
  String get testimonial4Review =>
      'Semplice, preciso e utile. Traccio le calorie senza problemi e mi sento più leggera durante il giorno.';

  @override
  String get yes => 'Sì';

  @override
  String get no => 'No';

  @override
  String get authenticationError => 'Authentication Error';

  @override
  String get registrationFailed => 'Registration Failed';

  @override
  String get loginFailed => 'Login Failed';

  @override
  String get networkError => 'Network Error';

  @override
  String get networkErrorDescription =>
      'Unable to connect to the server. Please check your internet connection and try again.';

  @override
  String get unexpectedError => 'Unexpected Error';

  @override
  String get unexpectedErrorDescription =>
      'Something went wrong. Please try again later.';

  @override
  String get tryAgain => 'Try Again';

  @override
  String get deleteExerciseTitle => 'Delete Exercise?';

  @override
  String get exerciseWillBePermanentlyDeleted =>
      'Exercise will be permanently deleted';

  @override
  String get failedToDeleteExercise =>
      'Failed to delete exercise. Please try again.';

  @override
  String get deleteMealTitle => 'Delete Meal?';

  @override
  String get mealWillBePermanentlyDeleted => 'Meal will be permanently deleted';

  @override
  String get howToScanProperly => 'How to scan properly';

  @override
  String get keepFoodInsideFrame => 'Keep food fully inside the frame';

  @override
  String get holdPhoneSteady => 'Hold your phone steady for a clear photo';

  @override
  String get takePictureStraight =>
      'Take the picture straight, not at an angle';

  @override
  String get successfullyAddedToDashboard => 'Successfully added to dashboard';
}
