// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Slovenian (`sl`).
class AppLocalizationsSl extends AppLocalizations {
  AppLocalizationsSl([String locale = 'sl']) : super(locale);

  @override
  String get appTitle => 'Kayree';

  @override
  String get home => 'Domov';

  @override
  String get analytics => 'Analitika';

  @override
  String get settings => 'Nastavitve';

  @override
  String get calories => 'kalorije';

  @override
  String get carbs => 'Ogljikovi hidrati';

  @override
  String get protein => 'Beljakovine';

  @override
  String get fats => 'Maščobe';

  @override
  String get setYourGoals => 'Nastavi svoje cilje';

  @override
  String get autoGenerate => 'Samodejno ustvari';

  @override
  String get autoGenerateDescription =>
      'Samodejno ustvari cilje z uporabo naprednih prehranskih algoritmov';

  @override
  String get noFoodLogged => 'Ni zabeležene hrane';

  @override
  String get tapPlusToTrack =>
      'Dotakni se + za spremljanje napredka in doseganje ciljev';

  @override
  String get analyzing => 'Analiziram hrano...';

  @override
  String achievedGoal(int percent) {
    return 'Dosegel si $percent% svojega cilja!';
  }

  @override
  String get database => 'Baza podatkov';

  @override
  String get gallery => 'Galerija';

  @override
  String get workout => 'Zabeleži vadbo';

  @override
  String get scanFood => 'Skeniraj hrano';

  @override
  String get log => 'Zabeleži';

  @override
  String get monday => 'Pon';

  @override
  String get tuesday => 'Tor';

  @override
  String get wednesday => 'Sre';

  @override
  String get thursday => 'Čet';

  @override
  String get friday => 'Pet';

  @override
  String get saturday => 'Sob';

  @override
  String get sunday => 'Ned';

  @override
  String get consistencyBuildsHealth => 'Doslednost gradi zdravje';

  @override
  String get healthHabitsDescription =>
      'Da dosežeš svoje cilje in ohraniš težo, vzpostavi rutino in razvij zdrave navade. Izzovi se in delaj na tem vsak dan.';

  @override
  String get positiveHealthEffects =>
      'Kmalu boš opazil pozitivne\nučinke na svoje zdravje';

  @override
  String get healthBenefits =>
      'Manjše tveganje za sladkorno bolezen, nižji\nkrvni tlak, boljši holesterol';

  @override
  String get enterReferralCode => 'Vnesi referenčno kodo';

  @override
  String get notRequired => '(ni obvezno)';

  @override
  String get influencerCode => 'Koda vplivneža';

  @override
  String get confirm => 'Potrdi';

  @override
  String get generateYourPlan => 'Ustvari svoj načrt';

  @override
  String get generatingYourPlan => 'Ustvarjamo tvoj\nosebni načrt';

  @override
  String get preparingFor => 'Priprava za';

  @override
  String get continue_ => 'Nadaljuj';

  @override
  String get startTrackingToday => 'Začni spremljati s\nKalorina že danes.';

  @override
  String get photoYourMeal => 'SAMO FOTOGRAFIRAJ\nSVOJ OBROK';

  @override
  String get photoYourMealDesc =>
      'Preprosto fotografiraj svoj obrok in samodejno prejmi informacije o kalorijah';

  @override
  String get totalCalories => 'NADZORUJ\nKALORIJE BREZ NAPORA';

  @override
  String get controlCaloriesEffortlessly =>
      'Spremljaj kalorije brez stresa in lažje kot kdajkoli dosezi svoje cilje';

  @override
  String get achieveGoalsFaster => 'DOSEZI CILJE HITREJE\nKOT KDAJKOLI';

  @override
  String get achieveGoalsDesc =>
      'Naša AI-tehnologija te bo korak za korakom vodila do tvojih ciljev';

  @override
  String get notificationReminder =>
      'Spomnili te bomo, preden se\ntvoja brezplačna preizkusna doba konča.';

  @override
  String get freeTrialInfo =>
      'Preizkusi za €0.00 – brez stroškov, če pravočasno prekličeš. Prekliči kadarkoli.';

  @override
  String get tryForFree => 'Preizkusi BREZPLAČNO';

  @override
  String get pricingTitle => '3 dni brezplačno, nato €39.99\nna leto.';

  @override
  String get day1 => 'Dan 1';

  @override
  String get day1Title => 'Odkleni Kalorina Pro';

  @override
  String get day1Description => 'Odkleni Kalorina Pro in razišči vse funkcije.';

  @override
  String get day2 => 'Dan 2';

  @override
  String get day2Title => 'Prijazen opomnik';

  @override
  String get day2Description =>
      'Prejmi prijazen opomnik, preden se preizkus konča.';

  @override
  String get day3 => 'Dan 3';

  @override
  String get day3Title => 'Nadaljuj z načrtom';

  @override
  String get day3Description => 'Nadaljuj z izbranim načrtom.';

  @override
  String get yearlyPlan => 'Letno – 3-dnevna brezplačna preizkusna doba';

  @override
  String get yearlyPrice => '€2.91 /mesec';

  @override
  String get monthlyPlan => 'Mesečno – brez brezplačne preizkusne dobe';

  @override
  String get startTrialButton => 'Začni 3-dnevni preizkus za €0.00';

  @override
  String get cancelAnytime => 'Prekliči kadarkoli';

  @override
  String get smarterWayTitle =>
      'Pametnejši način za spremljanje\ntega, kar ješ, se začne tukaj';

  @override
  String get noCalorieMath => 'Brez več računanja kalorij';

  @override
  String get noCalorieMathDesc => 'Mi naredimo izračune, ti pa uživaš v hrani.';

  @override
  String get scanTrackDone => 'Skeniraj. Spremljaj. Končano';

  @override
  String get scanTrackDoneDesc => 'Beleženje hrane traja le nekaj sekund.';

  @override
  String get stayOnTopEffortlessly => 'Ostani na pravi poti brez napora';

  @override
  String get stayOnTopEffortlesslyDesc =>
      'Nežni opomniki te ohranjajo doslednega.';

  @override
  String get language => 'Jezik';

  @override
  String get english => 'English';

  @override
  String get hrvatski => 'Hrvatski';

  @override
  String get srpski => 'Srpski';

  @override
  String get bosanski => 'Bosanski';

  @override
  String get slovenscina => 'Slovenščina';

  @override
  String get crnogorski => 'Crnogorski';

  @override
  String get makedonski => 'Македонски';

  @override
  String get bulgarski => 'Български';

  @override
  String get romana => 'Română';

  @override
  String get magyar => 'Magyar';

  @override
  String get appearance => 'Videz';

  @override
  String get light => 'Svetlo';

  @override
  String get dark => 'Temno';

  @override
  String get automatic => 'Samodejno';

  @override
  String get createYourAccount => 'Ustvari svoj račun';

  @override
  String get welcomeBack => 'Dobrodošel nazaj';

  @override
  String get continueWithApple => 'Nadaljuj z Apple';

  @override
  String get continueWithGoogle => 'Nadaljuj z Google';

  @override
  String get creatingAccount => 'Ustvarjanje računa...';

  @override
  String get wantToSignInLater => 'Se želiš prijaviti kasneje? ';

  @override
  String get skip => 'Preskoči';

  @override
  String get byContinuingAgree =>
      'Z nadaljevanjem se strinjaš z\nPogoji uporabe in Politiko zasebnosti';

  @override
  String get haveYouCountedCalories => 'Si že kdaj štel\nkalorije?';

  @override
  String get triedButStopped => 'Poskusil sem, a sem prenehal.';

  @override
  String get neverSeemComplex => 'Nikoli. Zdi se zapleteno.';

  @override
  String get yesStillDoing => 'Da, in še vedno to počnem.';

  @override
  String get logStreak => 'Log Streak';

  @override
  String get caloriesMoreToGo => 'Calories to go!';

  @override
  String get todaysLunchTotals => 'Today\'s lunch totals';

  @override
  String get mealTotals => 'Meal totals';

  @override
  String get consistencyMatters =>
      'Consistency matters for achieving your goals!';

  @override
  String get continueButton => 'Continue';

  @override
  String get kalorina => 'Kalorina';

  @override
  String get exercise => 'Exercise';

  @override
  String get cardio => 'Cardio';

  @override
  String get cardioSubtitle =>
      'Log runs, cycling, HIIT, or any endurance activity';

  @override
  String get weightTraining => 'Weight Training';

  @override
  String get weightTrainingSubtitle =>
      'Track gym sessions, sets, and strength exercises';

  @override
  String get describeExercise => 'Describe Exercise';

  @override
  String get describeExerciseSubtitle => 'Let AI calculate calories burned';

  @override
  String get directInput => 'Neposreden vnos';

  @override
  String get directInputSubtitle => 'Manual entry of calories burned';

  @override
  String get food => 'Food';

  @override
  String get myMeals => 'Moji obroki';

  @override
  String get myMealsSubtitle => 'Build a meal from your saved foods';

  @override
  String get myFoods => 'Moja hrana';

  @override
  String get myFoodsSubtitle => 'Create your own food database';

  @override
  String get savedScans => 'Shranjeni skeni';

  @override
  String get savedScansSubtitle => 'Find all previously saved foods';

  @override
  String get directInputFood => 'Direct Input';

  @override
  String get directInputFoodSubtitle =>
      'Manual entry of calories and macronutrients';

  @override
  String get howDoesItWork => 'How does it work?';

  @override
  String get currentStreak => 'Current streak';

  @override
  String get longestStreak => 'Longest streak';

  @override
  String get day => 'day';

  @override
  String get days => 'days';

  @override
  String get successfulDay => 'Successful day';

  @override
  String get failedDay => 'Failed day';

  @override
  String get undo => 'Undo';

  @override
  String get error => 'Error';

  @override
  String get success => 'Success';

  @override
  String get info => 'Info';

  @override
  String get failedToCreateStreak => 'Failed to create streak';

  @override
  String get streakUndoneFor => 'Streak undone for';

  @override
  String get noStreakToUndoFor => 'No streak to undo for';

  @override
  String get howDoesItWorkTitle => 'How does it work?';

  @override
  String get howDoesItWorkDescription =>
      'Every day, you can log your fire to reflect on whether you felt like you truly achieved what you wanted.';

  @override
  String get successfulDescription =>
      'Successful → You reached your daily goal or feel satisfied with your progress.';

  @override
  String get failedDescription =>
      'Failed → You didn\'t meet your goal or the day didn\'t go as planned.';

  @override
  String get streakExplanation =>
      'Your fires build streaks that show your consistency. The longer you log honestly, the clearer you\'ll see your real progress.';

  @override
  String get logExercise => 'Zabeleži vadbo';

  @override
  String get weightTrainingTab => 'Trening z utežmi';

  @override
  String get describeTab => 'Opiši';

  @override
  String get directInputTab => 'Neposreden vnos';

  @override
  String get low => 'Nizka';

  @override
  String get medium => 'Srednja';

  @override
  String get high => 'Visoka';

  @override
  String get intensity => 'Intenzivnost';

  @override
  String get duration => 'Trajanje';

  @override
  String get fifteenMin => '15 min';

  @override
  String get thirtyMin => '30 min';

  @override
  String get fortyFiveMin => '45 min';

  @override
  String get sixtyMin => '60 min';

  @override
  String get logging => 'Beleženje...';

  @override
  String get add => 'Dodaj';

  @override
  String get aiPowered => 'Poganja AI';

  @override
  String get explainWorkoutPlaceholder => 'Opiši trajanje vadbe, napor itd.';

  @override
  String get workoutExample =>
      'Primer: \"Trening zgornjega dela telesa, 45 min, srednji napor\"';

  @override
  String get estimating => 'Ocenjevanje...';

  @override
  String get aiEstimate => 'AI-ocena';

  @override
  String get whyThisEstimate => 'Zakaj ta ocena';

  @override
  String get typeCaloriesBurned => 'Ročno vnesi porabljene kalorije';

  @override
  String get zeroPlaceholder => '0';

  @override
  String get nearSprintingDescription =>
      'Skoraj sprint, težko vzdrževati dolgo';

  @override
  String get steadyRunDescription => 'Enakomeren tek, obvladljiv napor';

  @override
  String get briskWalkDescription => 'Hitra hoja, udobno dihanje';

  @override
  String get heavyWeightsDescription =>
      'Težke uteži, blizu maksimalnega napora';

  @override
  String get moderateWeightsDescription => 'Zmerne uteži, potenje';

  @override
  String get lightWeightsDescription => 'Lahke uteži, brez potenja';

  @override
  String get logFood => 'Zabeleži hrano';

  @override
  String get all => 'Vse';

  @override
  String get search => 'Search';

  @override
  String get searchMeals => 'Išči obroke...';

  @override
  String get searchFoods => 'Išči hrano...';

  @override
  String get searchScannedMeals => 'Išči skenirane obroke...';

  @override
  String get chickenBr => 'Piščančje prsi';

  @override
  String get suggestions => 'Predlogi';

  @override
  String get noSuggestionsAvailable => 'Ni razpoložljivih predlogov';

  @override
  String get noMealsSavedYet => 'Še ni shranjenih obrokov';

  @override
  String get noFoodsCreatedYet => 'Še ni ustvarjene hrane';

  @override
  String get createFood => 'Ustvari hrano';

  @override
  String get yourSavedScansWillAppearHere =>
      'Tvoji shranjeni skeni se bodo prikazali tukaj';

  @override
  String get savedScansContentComingSoon =>
      'Vsebina shranjenih skenov bo kmalu na voljo';

  @override
  String get editName => 'Uredi ime';

  @override
  String get caloriesLabel => 'Kalorije';

  @override
  String get caloriesPlaceholder => '512';

  @override
  String get ingredients => 'Sestavine';

  @override
  String get addMore => 'Dodaj več';

  @override
  String get amount => 'Količina';

  @override
  String get saveFood => 'Shrani hrano';

  @override
  String get createAMeal => 'Ustvari obrok';

  @override
  String get enterAmount => 'Vnesi količino';

  @override
  String get enterAmountPlaceholder => 'Vnesi količino';

  @override
  String get cancel => 'Prekliči';

  @override
  String get save => 'Shrani';

  @override
  String get name => 'Ime *';

  @override
  String get enterIngredientName => 'Vnesi ime sestavine';

  @override
  String get quantityUnit => 'Količina in enota';

  @override
  String get amountPlaceholder => 'Količina';

  @override
  String get unitPlaceholder => 'Enota (g, skodelica, žlica)';

  @override
  String get nutritionOptional => 'Prehrana (neobvezno)';

  @override
  String get caloriesPlaceholder2 => 'Kalorije';

  @override
  String get proteinG => 'Beljakovine (g)';

  @override
  String get carbsG => 'Ogljikovi hidrati (g)';

  @override
  String get fatG => 'Maščobe (g)';

  @override
  String get editIngredient => 'Uredi sestavino';

  @override
  String get addIngredient => 'Dodaj sestavino';

  @override
  String get scannedMeal => 'Skeniran obrok';

  @override
  String get setName => 'Nastavi ime';

  @override
  String get personalInformation => 'Osebni podatki';

  @override
  String get weight => 'Teža';

  @override
  String get height => 'Višina';

  @override
  String get age => 'Starost';

  @override
  String get gender => 'Spol';

  @override
  String get dailyStepsGoal => 'Dnevni cilj korakov';

  @override
  String get addBurnedCaloriesToGoal => 'Dodaj porabljene kalorije k cilju';

  @override
  String get account => 'Račun';

  @override
  String get manageYourProfileAndAccountSettings =>
      'Upravljaj svoj profil in nastavitve računa';

  @override
  String get healthTracking => 'Spremljanje zdravja';

  @override
  String get viewYourHealthConsistencyAndProgress =>
      'Oglej si svojo doslednost in napredek v zdravju';

  @override
  String get notifications => 'Obvestila';

  @override
  String get configureYourNotificationPreferences =>
      'Nastavi svoje nastavitve obvestil';

  @override
  String get about => 'O aplikaciji';

  @override
  String get appVersionAndInformation => 'Različica aplikacije in informacije';

  @override
  String get enterYourName => 'Vnesi svoje ime';

  @override
  String get selectGender => 'Izberi spol';

  @override
  String get male => 'Moški';

  @override
  String get female => 'Ženska';

  @override
  String get years => 'let';

  @override
  String get steps => 'korakov';

  @override
  String get progress => 'Napredek';

  @override
  String get myWeight => 'Moja teža';

  @override
  String get logWeight => 'Zabeleži težo';

  @override
  String get targetWeight => 'Ciljna teža';

  @override
  String get update => 'Posodobi';

  @override
  String get toTargetWeight => 'Do ciljne teže';

  @override
  String get weightGoalProgress => 'Napredek proti ciljni teži';

  @override
  String get thirtyDays => '30 dni';

  @override
  String get ninetyDays => '90 dni';

  @override
  String get sixMonths => '6 mesecev';

  @override
  String get oneYear => '1 leto';

  @override
  String get allTime => 'Ves čas';

  @override
  String get start => 'Začetek';

  @override
  String get now => 'Zdaj';

  @override
  String get avgDailyProgress => 'Povprečni dnevni napredek';

  @override
  String get avgDailyLost => 'Povprečno dnevno izgubljeno';

  @override
  String get avgDailyGained => 'Povprečno dnevno pridobljeno';

  @override
  String get addProgressPhoto => 'Dodaj fotografijo napredka';

  @override
  String get camera => 'Kamera';

  @override
  String get selectImageSource => 'Select Image Source';

  @override
  String get progressPhotos => 'Fotografije napredka';

  @override
  String get seeProgress => 'Oglej si napredek';

  @override
  String get uploadPhoto => 'Naloži fotografijo';

  @override
  String get upload => 'Naloži';

  @override
  String get stepsToday => 'Koraki danes';

  @override
  String get tapToEnableHealthPermissions =>
      'Dotakni se za omogočitev zdravstvenih dovoljenj';

  @override
  String get addBurnedCaloriesToDailyGoal =>
      'Dodaj porabljene kalorije k dnevnemu cilju';

  @override
  String get caloriesBurned => 'Porabljene kalorije';

  @override
  String get kg => 'kg';

  @override
  String get sinceLastWeighIn => 'od zadnjega tehtanja';

  @override
  String get kgPerDay => 'kg/dan';

  @override
  String get kgToGo => 'kg do cilja';

  @override
  String get greatJob => 'Odlično';

  @override
  String get youGained => 'Pridobil si';

  @override
  String get weighInDue => 'Čas je za tehtanje';

  @override
  String nextWeighIn(Object days) {
    return 'Naslednje tehtanje: ${days}d';
  }

  @override
  String get enterUsername => 'Vnesi uporabniško ime';

  @override
  String get birthday => 'Datum rojstva';

  @override
  String get personalDetails => 'Osebni podatki';

  @override
  String get rolloverLeftOverCalories =>
      'Prenesi do 200 preostalih kalorij od včeraj';

  @override
  String get addBurnedCalories => 'Dodaj porabljene kalorije';

  @override
  String get inviteFriends => 'Povabi prijatelje';

  @override
  String get adjustMacronutrients => 'Prilagodi makrohranila';

  @override
  String get support => 'Podpora';

  @override
  String get privacyPolicy => 'Pravilnik o zasebnosti';

  @override
  String get termsAndConditions => 'Pogoji in določila';

  @override
  String get deleteAccount => 'Izbriši račun';

  @override
  String get logout => 'Odjava';

  @override
  String get deleteAccountTitle => 'Izbrisati račun?';

  @override
  String get accountWillBePermanentlyDeleted => 'Račun bo trajno izbrisan';

  @override
  String get logoutTitle => 'Se želiš odjaviti?';

  @override
  String get areYouSureYouWantToLogOut =>
      'Ali si prepričan, da se želiš odjaviti?';

  @override
  String get recentlyUploaded => 'Nedavno naloženo';

  @override
  String get recentlyLogged => 'Recently Logged';

  @override
  String get cannotLogFutureStreak => 'Prihodnjih datumov ni mogoče zabeležiti';

  @override
  String get cannotLogFutureStreakDescription =>
      'Serije lahko beležiš le za danes in pretekle datume. Prihodnji datumi se bodo odklenili, ko pride njihov čas!';

  @override
  String dayStreak(int count) {
    return 'Dan $count v seriji';
  }

  @override
  String get keepGoing => 'Nadaljuj!';

  @override
  String get ok => 'V redu';

  @override
  String get whatWouldYouLikeToAchieve => 'Kaj želiš doseči?';

  @override
  String get stayMotivatedAndDisciplined => 'Ostani motiviran in discipliniran';

  @override
  String get feelBetterAboutYourBody => 'Počuti se bolje v svojem telesu';

  @override
  String get improveHealthLongTerm => 'Dolgoročno izboljšaj zdravje';

  @override
  String get increaseMoodAndEnergy => 'Povečaj razpoloženje in energijo';

  @override
  String get youHaveGreatPotential =>
      'Imaš velik potencial, da dosežeš svoj cilj';

  @override
  String get yourJourneyToBetterHealth =>
      'Tvoja pot do boljšega zdravja se začne zdaj';

  @override
  String get youTookFirstStepToHealthier =>
      'Naredil si prvi korak k bolj zdravi različici sebe';

  @override
  String get trackYourFoodAndExercise => 'Spremljaj svojo hrano in vadbo';

  @override
  String get focusOnNutrientDenseFoods =>
      'Osredotoči se na hrano, bogato s hranili';

  @override
  String get maintainYourHealthyHabits => 'Ohranjaj svoje zdrave navade';

  @override
  String get balanceCarbsProteinAndFats =>
      'Uravnoteži ogljikove hidrate, beljakovine in maščobe';

  @override
  String get stickToYourPersonalizedPlan =>
      'Drži se svojega prilagojenega načrta';

  @override
  String get focusOnWholeUnprocessedFoods =>
      'Osredotoči se na celostno, nepredelano hrano';

  @override
  String get followYourPersonalizedMealPlan =>
      'Sledi svojemu prilagojenemu načrtu obrokov';

  @override
  String get focusOnPortionControlAndNutrition =>
      'Osredotoči se na nadzor porcij in prehrano';

  @override
  String get followYourPersonalizedPlan => 'Sledi svojemu prilagojenemu načrtu';

  @override
  String get stayConsistentSeeRealResults =>
      'Ostani dosleden in vidi prave rezultate';

  @override
  String get enableNotificationsForBetterResults =>
      'Omogoči obvestila za boljše rezultate';

  @override
  String get recommended => '(Priporočeno)';

  @override
  String get kalorinaHelpsYouKeepTrack =>
      'Kalorina ti pomaga ostati na pravi poti — prejmi dnevne opomnike';

  @override
  String get dontAllow => 'Ne dovoli';

  @override
  String get allow => 'Dovoli';

  @override
  String get countBurnedCaloriesTowardsGoal =>
      'Vključi porabljene kalorije v dnevni cilj?';

  @override
  String get todaysGoal => 'Današnji cilj:';

  @override
  String get stepsLabel => 'Koraki:';

  @override
  String get transferExtraCaloriesToNextDay =>
      'Prenesi dodatne kalorije na naslednji dan?';

  @override
  String get yesterday => 'Včeraj';

  @override
  String get today => 'Danes';

  @override
  String get caloriesLeft => 'Preostale kalorije';

  @override
  String get everydayLogFireReflect =>
      'Vsak dan lahko zabeležiš 🔥 in razmisliš, ali si res dosegel, kar si si zadal. Tvoji 🔥 ustvarjajo serije, ki kažejo tvojo doslednost.';

  @override
  String get longLastingHealthEffects =>
      'Opazil boš dolgotrajne učinke na svoje zdravje';

  @override
  String get ninetyPercent => '90%';

  @override
  String get usersStayConsistentMaintainWeight =>
      ' uporabnikov, ki ostanejo dosledni, ohranja svojo težo tudi ';

  @override
  String get twelveMonthsLater => '12 mesecev kasneje';

  @override
  String get leaveUsReview => 'Pusti nam oceno';

  @override
  String get joinOver10000People =>
      'Pridruži se več kot 10.000\nljudem, ki so prav takšni kot ti';

  @override
  String get applied => 'Uporabljeno';

  @override
  String get howItWorksUniqueApproach =>
      'Kako deluje edinstven\npristop Kalorina';

  @override
  String get scan => 'Skeniraj';

  @override
  String get analyze => 'Analiziraj';

  @override
  String get track => 'Spremljaj';

  @override
  String get heightAndWeight => 'Višina in teža';

  @override
  String get heightWeightSubtitle =>
      'Te informacije nam pomagajo prilagoditi tvoje dnevne kalorične in prehranske cilje.';

  @override
  String get imperial => 'Imperialno';

  @override
  String get metric => 'Metrično';

  @override
  String get heightLabel => 'Višina';

  @override
  String get weightLabel => 'Teža';

  @override
  String get whenWereYouBorn => 'Kdaj si se rodil?';

  @override
  String get birthDateSubtitle =>
      'To upoštevamo pri izračunu tvojih dnevnih prehranskih ciljev.';

  @override
  String get monthLabel => 'Mesec';

  @override
  String get dayLabel => 'Dan';

  @override
  String get yearLabel => 'Leto';

  @override
  String get january => 'Januar';

  @override
  String get february => 'Februar';

  @override
  String get march => 'Marec';

  @override
  String get april => 'April';

  @override
  String get may => 'Maj';

  @override
  String get june => 'Junij';

  @override
  String get july => 'Julij';

  @override
  String get august => 'Avgust';

  @override
  String get september => 'September';

  @override
  String get october => 'Oktober';

  @override
  String get november => 'November';

  @override
  String get december => 'December';

  @override
  String get selectYourGender => 'Izberi svoj spol';

  @override
  String get genderSelectionInfo =>
      'Izberi spol, ki ustreza fiziologiji tvojega telesa za natančno spremljanje kalorij';

  @override
  String get maleGender => 'Moški';

  @override
  String get femaleGender => 'Ženska';

  @override
  String get howManyWorkoutsPerWeek => 'Koliko treningov opraviš na teden';

  @override
  String get selectBestOption => 'Izberi možnost, ki ti najbolj ustreza';

  @override
  String get noWorkouts => 'Ne treniram';

  @override
  String get occasionalWorkouts => 'Občasni treningi';

  @override
  String get severalWorkoutsWeekly => 'Več treningov na teden';

  @override
  String get dedicatedAthlete => 'Predani športnik';

  @override
  String get whereDidYouHearAboutUs => 'Kje si slišal za nas?';

  @override
  String get googlePlay => 'Google Play';

  @override
  String get youtube => 'YouTube';

  @override
  String get tiktok => 'TikTok';

  @override
  String get instagram => 'Instagram';

  @override
  String get influencer => 'Vplivnež';

  @override
  String get friendsOrFamily => 'Prijatelji ali družina';

  @override
  String get other => 'Drugo';

  @override
  String get wellDoneBigStep => 'Bravo! Pravkar si naredil\nvelik korak.';

  @override
  String get calorieTrackingPart1 => 'Ali si vedel, da je spremljanje kalorij ';

  @override
  String get scientificallyProvenMethod => 'znanstveno dokazana metoda';

  @override
  String get calorieTrackingPart2 =>
      ' za doseganje tvojih ciljev – in celo do ';

  @override
  String get twiceFaster => 'dvakrat hitreje';

  @override
  String get calorieTrackingPart3 => '?';

  @override
  String get yourProgress => 'Tvoj napredek';

  @override
  String get withKalorina => 'S Kalorina';

  @override
  String get withoutKalorina => 'Brez Kalorina';

  @override
  String get twiceMultiplier => '+2x';

  @override
  String get whatIsYourGoal => 'Kakšen je tvoj cilj';

  @override
  String get selectGoalThatSuitsYou => 'Izberi cilj, ki ti najbolj ustreza';

  @override
  String get loseWeight => 'Izgubiti težo';

  @override
  String get maintainWeight => 'Ohranjati težo';

  @override
  String get gainWeight => 'Pridobiti težo';

  @override
  String get howMuchWeightToLose => 'Koliko teže želiš izgubiti?';

  @override
  String get howMuchWeightToGain => 'Koliko teže želiš pridobiti?';

  @override
  String get whatIsDesiredWeight => 'Kakšna je tvoja želena teža?';

  @override
  String get isRealisticGoal => 'je realen cilj.';

  @override
  String get youHaveGreatPotentialLose =>
      'Imaš velik potencial, da dosežeš svoj cilj!\nNaredimo to skupaj!';

  @override
  String get youHaveGreatPotentialGain =>
      'Gradnja mišic zahteva predanost!\nTukaj smo, da te podpiramo na tvoji poti!';

  @override
  String get youveGotThis => 'Zmoreš!';

  @override
  String get stayStrong => 'Ostani močan!';

  @override
  String get nineOutOfTenUsers =>
      '9 od 10 uporabnikov pravi, da\nvidijo rezultate v prvem tednu\nuporabe Kalorina';

  @override
  String get pickWeightLossSpeed => 'Izberi hitrost izgube teže';

  @override
  String get pickWeightGainSpeed => 'Izberi hitrost pridobivanja teže';

  @override
  String get theSafestOption => 'Najvarnejša možnost';

  @override
  String get balancedApproach => 'Uravnotežen pristop';

  @override
  String get aggressivePlan => 'Agresiven načrt';

  @override
  String get doYouFollowDiet => 'Ali slediš določeni dieti?';

  @override
  String get helpTrackCaloriesDiet =>
      'Pomagali ti bomo spremljati kalorije glede na tvojo dieto';

  @override
  String get classic => 'Klasična';

  @override
  String get carnivore => 'Mesojeda';

  @override
  String get keto => 'Keto';

  @override
  String get vegan => 'Veganska';

  @override
  String get vegetarian => 'Vegetarijanska';

  @override
  String get wereHereForYou => 'Tukaj smo zate!';

  @override
  String get journeySupportMessage =>
      'Pot do tvojega cilja je lahko včasih zahtevna, a tukaj smo, da te podpiramo na vsakem koraku. Ne boš se moral soočiti s tem sam.';

  @override
  String get starsAcrossApps => 'Zvezdice v aplikacijah';

  @override
  String get testimonial1Name => 'Luka J.';

  @override
  String get testimonial1Review =>
      'Aplikacija je neverjetno natančna. Končno vem, koliko pojem, in čez dan se počutim veliko bolje.';

  @override
  String get testimonial2Name => 'Marko P.';

  @override
  String get testimonial2Review =>
      'Odkar uporabljam aplikacijo, bolje razumem porcije. Jem pametneje in imam čez dan več energije.';

  @override
  String get testimonial3Name => 'Jelena K.';

  @override
  String get testimonial3Review =>
      'Natančnost vnosa me je navdušila. Končno imam nadzor nad kalorijami brez stresa in štetja.';

  @override
  String get testimonial4Name => 'Emir S.';

  @override
  String get testimonial4Review =>
      'Popolno za dnevno rutino. Hitro skeniram obroke in napredek opazim že po enem tednu.';

  @override
  String get yes => 'Da';

  @override
  String get no => 'Ne';

  @override
  String get authenticationError => 'Authentication Error';

  @override
  String get registrationFailed => 'Registration Failed';

  @override
  String get loginFailed => 'Login Failed';

  @override
  String get networkError => 'Network Error';

  @override
  String get networkErrorDescription =>
      'Unable to connect to the server. Please check your internet connection and try again.';

  @override
  String get unexpectedError => 'Unexpected Error';

  @override
  String get unexpectedErrorDescription =>
      'Something went wrong. Please try again later.';

  @override
  String get tryAgain => 'Try Again';

  @override
  String get deleteExerciseTitle => 'Delete Exercise?';

  @override
  String get exerciseWillBePermanentlyDeleted =>
      'Exercise will be permanently deleted';

  @override
  String get failedToDeleteExercise =>
      'Failed to delete exercise. Please try again.';

  @override
  String get deleteMealTitle => 'Delete Meal?';

  @override
  String get mealWillBePermanentlyDeleted => 'Meal will be permanently deleted';

  @override
  String get howToScanProperly => 'How to scan properly';

  @override
  String get keepFoodInsideFrame => 'Keep food fully inside the frame';

  @override
  String get holdPhoneSteady => 'Hold your phone steady for a clear photo';

  @override
  String get takePictureStraight =>
      'Take the picture straight, not at an angle';

  @override
  String get successfullyAddedToDashboard => 'Successfully added to dashboard';
}
