// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Slovenian (`sl`).
class AppLocalizationsSl extends AppLocalizations {
  AppLocalizationsSl([String locale = 'sl']) : super(locale);

  @override
  String get appTitle => 'Karolina';

  @override
  String get home => 'Domov';

  @override
  String get analytics => 'Analitika';

  @override
  String get settings => 'Nastavitve';

  @override
  String get calories => 'kalorije';

  @override
  String get carbs => 'Ogljikovi Hidrati';

  @override
  String get protein => 'Beljakovine';

  @override
  String get fats => 'Maščobe';

  @override
  String get setYourGoals => 'Nastavi Svoje Cilje';

  @override
  String get autoGenerate => 'Samodejno Ustvari';

  @override
  String get autoGenerateDescription =>
      'Samodejno ustvari cilje z uporabo strokovnih prehranskih algoritmov';

  @override
  String get noFoodLogged => 'Ni zabeležene hrane';

  @override
  String get tapPlusToTrack =>
      'Dotaknite se + za spremljanje napredka in doseganje ciljev';

  @override
  String get analyzing => 'Analiziram hrano...';

  @override
  String achievedGoal(int percent) {
    return 'Dosegli ste $percent% svojega cilja!';
  }

  @override
  String get database => 'Podatkovna Baza';

  @override
  String get gallery => 'Galerija';

  @override
  String get workout => 'Zabeleži Vadbo';

  @override
  String get scanFood => 'Skeniraj Hrano';

  @override
  String get log => 'Dnevnik';

  @override
  String get monday => 'Pon';

  @override
  String get tuesday => 'Tor';

  @override
  String get wednesday => 'Sre';

  @override
  String get thursday => 'Čet';

  @override
  String get friday => 'Pet';

  @override
  String get saturday => 'Sob';

  @override
  String get sunday => 'Ned';

  @override
  String get consistencyBuildsHealth => 'Doslednost gradi zdravje';

  @override
  String get healthHabitsDescription =>
      'To hit your goals and keep the weight, set a routine and make a healthy habits. Challenge your and work on it every day.';

  @override
  String get positiveHealthEffects =>
      'You\'ll see positive effects\non your health soon';

  @override
  String get healthBenefits =>
      'Reduced risk of diabetes, lower blood\npressure, improved cholesterol levels';

  @override
  String get enterReferralCode => 'Vnesite referenčno kodo';

  @override
  String get notRequired => '(ni obvezno)';

  @override
  String get influencerCode => 'Koda Vplivneža';

  @override
  String get confirm => 'Potrdi';

  @override
  String get generateYourPlan => 'Ustvari svoj načrt';

  @override
  String get generatingYourPlan => 'Ustvarjamo vaš\npriljubljen načrt';

  @override
  String get preparingFor => 'Priprava za';

  @override
  String get continue_ => 'Nadaljuj';

  @override
  String get startTrackingToday => 'Start tracking with\nKalorina today.';

  @override
  String get photoYourMeal => 'SAMO FOTOGRAFIRAJ\nSVOJ OBROK';

  @override
  String get photoYourMealDesc =>
      'Preprosto fotografiraj svoj obrok in samodejno dobiš informacije o kalorijah';

  @override
  String get totalCalories => 'NADZORUJ\nKALORIJE BREZ TEŽAV';

  @override
  String get controlCaloriesEffortlessly =>
      'Sledi kalorijam brez stresa in dosegaj svoje cilje lažje kot kdajkoli prej';

  @override
  String get achieveGoalsFaster => 'DOSEZI CILJE HITREJE\nKOT KDAJKOLI';

  @override
  String get achieveGoalsDesc =>
      'Naša AI tehnologija te bo vodila korak za korakom do tvojih ciljev';

  @override
  String get notificationReminder =>
      'We\'ll remind you before\nyour free trial ends.';

  @override
  String get freeTrialInfo =>
      'Preizkusi za €0.00 - Brez stroškov, če prekličeš pravočasno. Prekliči kadarkoli.';

  @override
  String get tryForFree => 'Preizkusi BREZPLAČNO';

  @override
  String get pricingTitle => '3 days free, then €39.99\nper year.';

  @override
  String get day1 => 'Day 1';

  @override
  String get day1Title => 'Odkleni Kalorina Pro';

  @override
  String get day1Description => 'Unlock Kalorina Pro and explore everything.';

  @override
  String get day2 => 'Day 2';

  @override
  String get day2Title => 'Prijazen opomnik';

  @override
  String get day2Description =>
      'Get a friendly reminder before your trial ends.';

  @override
  String get day3 => 'Day 3';

  @override
  String get day3Title => 'Nadaljuj z načrtom';

  @override
  String get day3Description => 'Continue with your chosen plan.';

  @override
  String get yearlyPlan => 'Yearly - 3 Day Free Trial';

  @override
  String get yearlyPrice => '€2.91 /mo';

  @override
  String get monthlyPlan => 'Monthly - No Free Trial';

  @override
  String get startTrialButton => 'Start My 3-Day Trial For €0.00';

  @override
  String get cancelAnytime => 'Prekliči kadarkoli';

  @override
  String get smarterWayTitle =>
      'Your smarter way to track\nwhat you eat starts here';

  @override
  String get noCalorieMath => 'No more calorie math';

  @override
  String get noCalorieMathDesc => 'We do the numbers, you enjoy the food.';

  @override
  String get scanTrackDone => 'Scan. Track. Done';

  @override
  String get scanTrackDoneDesc => 'Logging food takes seconds.';

  @override
  String get stayOnTopEffortlessly => 'Stay on top effortlessly';

  @override
  String get stayOnTopEffortlesslyDesc =>
      'Gentle reminders keep you consistent.';

  @override
  String get language => 'Jezik';

  @override
  String get english => 'English';

  @override
  String get hrvatski => 'Hrvatski';

  @override
  String get srpski => 'Srpski';

  @override
  String get bosanski => 'Bosanski';

  @override
  String get slovenscina => 'Slovenščina';

  @override
  String get crnogorski => 'Crnogorski';

  @override
  String get makedonski => 'Македонски';

  @override
  String get bulgarski => 'Български';

  @override
  String get romana => 'Română';

  @override
  String get magyar => 'Magyar';

  @override
  String get appearance => 'Videz';

  @override
  String get light => 'Svetlo';

  @override
  String get dark => 'Temno';

  @override
  String get automatic => 'Samodejno';

  @override
  String get createYourAccount => 'Ustvari Svoj Račun';

  @override
  String get welcomeBack => 'Dobrodošel Nazaj';

  @override
  String get continueWithApple => 'Nadaljuj z Apple';

  @override
  String get continueWithGoogle => 'Nadaljuj z Google';

  @override
  String get creatingAccount => 'Ustvarjanje računa...';

  @override
  String get wantToSignInLater => 'Se želiš prijaviti kasneje? ';

  @override
  String get skip => 'Preskoči';

  @override
  String get byContinuingAgree =>
      'Z nadaljevanjem se strinjaš z našimi\nPogoji uporabe in Politiko zasebnosti';

  @override
  String get haveYouCountedCalories => 'Ste že kdaj šteli\nkalorije?';

  @override
  String get triedButStopped => 'Poskusil/a sem, a sem prenehal/a.';

  @override
  String get neverSeemComplex => 'Nikoli. Zdi se zapleteno.';

  @override
  String get yesStillDoing => 'Da, in še vedno to počnem.';

  @override
  String get logStreak => 'Log Streak';

  @override
  String get caloriesMoreToGo => 'Calories more to go!';

  @override
  String get todaysLunchTotals => 'Today\'s lunch totals';

  @override
  String get mealTotals => 'Meal totals';

  @override
  String get consistencyMatters =>
      'Consistency matters for achieving your goals!';

  @override
  String get continueButton => 'Continue';

  @override
  String get kalorina => 'Kalorina';

  @override
  String get exercise => 'Exercise';

  @override
  String get cardio => 'Cardio';

  @override
  String get cardioSubtitle =>
      'Log runs, cycling, HIIT, or any endurance activity';

  @override
  String get weightTraining => 'Weight Training';

  @override
  String get weightTrainingSubtitle =>
      'Track gym sessions, sets, and strength exercises';

  @override
  String get describeExercise => 'Describe Exercise';

  @override
  String get describeExerciseSubtitle => 'Let AI calculate calories burned';

  @override
  String get directInput => 'Direkten Vnos';

  @override
  String get directInputSubtitle => 'Manual entry of calories burned';

  @override
  String get food => 'Food';

  @override
  String get myMeals => 'Moji Obroki';

  @override
  String get myMealsSubtitle => 'Build a meal from your saved foods';

  @override
  String get myFoods => 'Moja Hrana';

  @override
  String get myFoodsSubtitle => 'Create your own food database';

  @override
  String get savedScans => 'Shranjeni Skeni';

  @override
  String get savedScansSubtitle => 'Find all previously saved foods';

  @override
  String get directInputFood => 'Direct Input';

  @override
  String get directInputFoodSubtitle =>
      'Manual entry of calories and macronutrients';

  @override
  String get howDoesItWork => 'How does it work?';

  @override
  String get currentStreak => 'Current streak';

  @override
  String get longestStreak => 'Longest streak';

  @override
  String get day => 'day';

  @override
  String get days => 'days';

  @override
  String get successfulDay => 'Successful day';

  @override
  String get failedDay => 'Failed day';

  @override
  String get undo => 'Undo';

  @override
  String get error => 'Error';

  @override
  String get success => 'Success';

  @override
  String get info => 'Info';

  @override
  String get failedToCreateStreak => 'Failed to create streak';

  @override
  String get streakUndoneFor => 'Streak undone for';

  @override
  String get noStreakToUndoFor => 'No streak to undo for';

  @override
  String get howDoesItWorkTitle => 'How does it work?';

  @override
  String get howDoesItWorkDescription =>
      'Every day, you can log your fire to reflect on whether you felt like you truly achieved what you wanted.';

  @override
  String get successfulDescription =>
      'Successful → You reached your daily goal or feel satisfied with your progress.';

  @override
  String get failedDescription =>
      'Failed → You didn\'t meet your goal or the day didn\'t go as planned.';

  @override
  String get streakExplanation =>
      'Your fires build streaks that show your consistency. The longer you log honestly, the clearer you\'ll see your real progress.';

  @override
  String get logExercise => 'Zabeleži vajo';

  @override
  String get weightTrainingTab => 'Trening z utežmi';

  @override
  String get describeTab => 'Opiši';

  @override
  String get directInputTab => 'Neposreden vnos';

  @override
  String get low => 'Nizka';

  @override
  String get medium => 'Srednja';

  @override
  String get high => 'Visoka';

  @override
  String get intensity => 'Intenzivnost';

  @override
  String get duration => 'Trajanje';

  @override
  String get fifteenMin => '15 min';

  @override
  String get thirtyMin => '30 min';

  @override
  String get fortyFiveMin => '45 min';

  @override
  String get sixtyMin => '60 min';

  @override
  String get logging => 'Beleženje...';

  @override
  String get add => 'Dodaj';

  @override
  String get aiPowered => 'Poganja AI';

  @override
  String get explainWorkoutPlaceholder => 'Razloži trajanje vadbe, napor, itd.';

  @override
  String get workoutExample =>
      'Primer: \"Trening zgornjega dela telesa, 45 min, srednji napor\"';

  @override
  String get estimating => 'Ocenjevanje...';

  @override
  String get aiEstimate => 'AI ocena';

  @override
  String get whyThisEstimate => 'Zakaj ta ocena';

  @override
  String get typeCaloriesBurned => 'Vnesi porabljene kalorije sam';

  @override
  String get zeroPlaceholder => '0';

  @override
  String get nearSprintingDescription =>
      'Skoraj sprint, težko vzdrževati dolgo';

  @override
  String get steadyRunDescription => 'Stabilno tečanje, obvladljiv napor';

  @override
  String get briskWalkDescription => 'Hitra hoja, udobno dihanje';

  @override
  String get heavyWeightsDescription =>
      'Težke uteži, blizu maksimalnega napora';

  @override
  String get moderateWeightsDescription => 'Zmerne uteži, potenje';

  @override
  String get lightWeightsDescription => 'Lahke uteži, brez potenja';

  @override
  String get logFood => 'Zabeleži Hrano';

  @override
  String get all => 'Vse';

  @override
  String get search => 'Search';

  @override
  String get searchMeals => 'Išči obroke...';

  @override
  String get searchFoods => 'Išči hrano...';

  @override
  String get searchScannedMeals => 'Išči skenirane obroke...';

  @override
  String get chickenBr => 'Piščanec br';

  @override
  String get suggestions => 'Predlogi';

  @override
  String get noSuggestionsAvailable => 'Ni na voljo predlogov';

  @override
  String get noMealsSavedYet => 'Še ni shranjenih obrokov';

  @override
  String get noFoodsCreatedYet => 'Še ni ustvarjene hrane';

  @override
  String get createFood => 'Ustvari Hrano';

  @override
  String get yourSavedScansWillAppearHere =>
      'Vaši shranjeni skeni se bodo prikazali tukaj';

  @override
  String get savedScansContentComingSoon => 'Vsebina shranjenih skenov kmalu';

  @override
  String get editName => 'Uredi Ime';

  @override
  String get caloriesLabel => 'Kalorije';

  @override
  String get caloriesPlaceholder => '512';

  @override
  String get ingredients => 'Sestavine';

  @override
  String get addMore => 'Dodaj Več';

  @override
  String get amount => 'Količina';

  @override
  String get saveFood => 'Shrani Hrano';

  @override
  String get createAMeal => 'Ustvari Obrok';

  @override
  String get enterAmount => 'Vnesi Količino';

  @override
  String get enterAmountPlaceholder => 'Vnesi količino';

  @override
  String get cancel => 'Prekliči';

  @override
  String get save => 'Shrani';

  @override
  String get name => 'Ime *';

  @override
  String get enterIngredientName => 'Vnesi ime sestavine';

  @override
  String get quantityUnit => 'Količina in Enota';

  @override
  String get amountPlaceholder => 'Količina';

  @override
  String get unitPlaceholder => 'Enota (g, skodelica, žlica)';

  @override
  String get nutritionOptional => 'Prehrana (Neobvezno)';

  @override
  String get caloriesPlaceholder2 => 'Kalorije';

  @override
  String get proteinG => 'Beljakovine (g)';

  @override
  String get carbsG => 'Ogljikovi Hidrati (g)';

  @override
  String get fatG => 'Maščobe (g)';

  @override
  String get editIngredient => 'Uredi Sestavino';

  @override
  String get addIngredient => 'Dodaj Sestavino';

  @override
  String get scannedMeal => 'Skeniran Obrok';

  @override
  String get setName => 'Nastavi Ime';

  @override
  String get personalInformation => 'Osebne Informacije';

  @override
  String get weight => 'Teža';

  @override
  String get height => 'Višina';

  @override
  String get age => 'Starost';

  @override
  String get gender => 'Spol';

  @override
  String get dailyStepsGoal => 'Dnevni cilj korakov';

  @override
  String get addBurnedCaloriesToGoal => 'Dodaj Porabljene Kalorije k Cilju';

  @override
  String get account => 'Račun';

  @override
  String get manageYourProfileAndAccountSettings =>
      'Upravljaj svojim profilom in nastavitvami računa';

  @override
  String get healthTracking => 'Sledenje Zdravju';

  @override
  String get viewYourHealthConsistencyAndProgress =>
      'Oglej si svojo zdravstveno doslednost in napredek';

  @override
  String get notifications => 'Obvestila';

  @override
  String get configureYourNotificationPreferences =>
      'Konfiguriraj svoje nastavitve obvestil';

  @override
  String get about => 'O Aplikaciji';

  @override
  String get appVersionAndInformation => 'Verzija aplikacije in informacije';

  @override
  String get enterYourName => 'Vnesi svoje ime';

  @override
  String get selectGender => 'Izberi Spol';

  @override
  String get male => 'Moški';

  @override
  String get female => 'Ženski';

  @override
  String get years => 'let';

  @override
  String get steps => 'korakov';

  @override
  String get progress => 'Napredek';

  @override
  String get myWeight => 'Moja Teža';

  @override
  String get logWeight => 'Zabeleži Težo';

  @override
  String get targetWeight => 'Ciljna Teža';

  @override
  String get update => 'Posodobi';

  @override
  String get toTargetWeight => 'K ciljni teži';

  @override
  String get weightGoalProgress => 'Napredek Ciljne Teže';

  @override
  String get thirtyDays => '30 Dni';

  @override
  String get ninetyDays => '90 Dni';

  @override
  String get sixMonths => '6 Mesecev';

  @override
  String get oneYear => '1 Leto';

  @override
  String get allTime => 'Ves Čas';

  @override
  String get start => 'Začetek';

  @override
  String get now => 'Sedaj';

  @override
  String get avgDailyProgress => 'Povprečni dnevni napredek';

  @override
  String get avgDailyLost => 'Povprečno dnevno izgubljeno';

  @override
  String get avgDailyGained => 'Povprečno dnevno pridobljeno';

  @override
  String get addProgressPhoto => 'Dodaj Fotografijo Napredka';

  @override
  String get camera => 'Kamera';

  @override
  String get selectImageSource => 'Select Image Source';

  @override
  String get progressPhotos => 'Fotografije Napredka';

  @override
  String get seeProgress => 'Poglej napredek';

  @override
  String get uploadPhoto => 'Naloži Fotografijo';

  @override
  String get upload => 'Naloži';

  @override
  String get stepsToday => 'Koraki Danes';

  @override
  String get tapToEnableHealthPermissions =>
      'Dotakni se za omogočitev zdravstvenih dovoljenj';

  @override
  String get addBurnedCaloriesToDailyGoal =>
      'Dodaj porabljene kalorije k dnevnemu cilju';

  @override
  String get caloriesBurned => 'Porabljene Kalorije';

  @override
  String get kg => 'kg';

  @override
  String get sinceLastWeighIn => 'od zadnjega tehtanja';

  @override
  String get kgPerDay => 'kg/dan';

  @override
  String get kgToGo => 'kg do cilja';

  @override
  String get greatJob => 'Odlično';

  @override
  String get youGained => 'Dobil si';

  @override
  String get weighInDue => 'Tehtanje potrebno';

  @override
  String nextWeighIn(Object days) {
    return 'Naslednje tehtanje: ${days}d';
  }

  @override
  String get enterUsername => 'Vnesite uporabniško ime';

  @override
  String get birthday => 'Rojstni dan';

  @override
  String get personalDetails => 'Osebni podatki';

  @override
  String get rolloverLeftOverCalories =>
      'Prenesi do 200 preostalih kalorij od včeraj';

  @override
  String get addBurnedCalories => 'Dodaj porabljene kalorije';

  @override
  String get inviteFriends => 'Povabi prijatelje';

  @override
  String get adjustMacronutrients => 'Prilagodi makronutriente';

  @override
  String get support => 'Podpora';

  @override
  String get privacyPolicy => 'Pravilnik o zasebnosti';

  @override
  String get termsAndConditions => 'Pogoji in določila';

  @override
  String get deleteAccount => 'Izbriši račun';

  @override
  String get logout => 'Odjava';

  @override
  String get deleteAccountTitle => 'Izbrisati račun?';

  @override
  String get accountWillBePermanentlyDeleted => 'Račun bo trajno izbrisan';

  @override
  String get logoutTitle => 'Odjaviti se?';

  @override
  String get areYouSureYouWantToLogOut =>
      'Ali ste prepričani, da se želite odjaviti?';

  @override
  String get recentlyUploaded => 'Nedavno naloženo';

  @override
  String get recentlyLogged => 'Recently Logged';

  @override
  String get cannotLogFutureStreak =>
      'Ni mogoče evidentirati prihodnjih datumov';

  @override
  String get cannotLogFutureStreakDescription =>
      'Lahko evidentirate nize samo za danes in pretekle datume. Prihodnji datumi se bodo odklenili, ko bodo prispeli!';

  @override
  String dayStreak(int count) {
    return 'Dan $count Niz';
  }

  @override
  String get keepGoing => 'Nadaljuj!';

  @override
  String get ok => 'V redu';

  @override
  String get whatWouldYouLikeToAchieve => 'Kaj bi radi dosegli?';

  @override
  String get stayMotivatedAndDisciplined => 'Ostati motiviran in discipliniran';

  @override
  String get feelBetterAboutYourBody =>
      'Počutiti se bolje glede svojega telesa';

  @override
  String get improveHealthLongTerm => 'Dolgoročno izboljšati zdravje';

  @override
  String get increaseMoodAndEnergy => 'Povečati razpoloženje in energijo';

  @override
  String get youHaveGreatPotential =>
      'Imaš velik potencial za dosego svojega cilja';

  @override
  String get yourJourneyToBetterHealth =>
      'Tvoja pot do boljšega zdravja se začne zdaj';

  @override
  String get youTookFirstStepToHealthier =>
      'Naredil si prvi korak k bolj zdravi različici sebe';

  @override
  String get trackYourFoodAndExercise => 'Sledi svoji hrani in vadbi';

  @override
  String get focusOnNutrientDenseFoods =>
      'Osredotoči se na hrano, bogato s hranili';

  @override
  String get maintainYourHealthyHabits => 'Ohranjaj svoje zdrave navade';

  @override
  String get balanceCarbsProteinAndFats =>
      'Uravnoteži ogljikove hidrate, beljakovine in maščobe';

  @override
  String get stickToYourPersonalizedPlan =>
      'Drži se svojega personaliziranega načrta';

  @override
  String get focusOnWholeUnprocessedFoods =>
      'Osredotoči se na celostno, neobdelano hrano';

  @override
  String get followYourPersonalizedMealPlan =>
      'Sledi svojemu personaliziranemu načrtu obrokov';

  @override
  String get focusOnPortionControlAndNutrition =>
      'Osredotoči se na nadzor porcij in prehrano';

  @override
  String get followYourPersonalizedPlan =>
      'Sledi svojemu personaliziranemu načrtu';

  @override
  String get stayConsistentSeeRealResults =>
      'Ostani dosleden, vidi prave rezultate';

  @override
  String get enableNotificationsForBetterResults =>
      'Omogoči obvestila za boljše rezultate';

  @override
  String get recommended => '(Priporočeno)';

  @override
  String get kalorinaHelpsYouKeepTrack =>
      'Kalorina ti pomaga slediti — Prejemaj dnevne opomnike';

  @override
  String get dontAllow => 'Ne dovoli';

  @override
  String get allow => 'Dovoli';

  @override
  String get countBurnedCaloriesTowardsGoal =>
      'Štetje zažganih kalorij za dnevni cilj?';

  @override
  String get todaysGoal => 'Današnji cilj:';

  @override
  String get stepsLabel => 'Koraki:';

  @override
  String get transferExtraCaloriesToNextDay =>
      'Prenesi dodatne kalorije na naslednji dan?';

  @override
  String get yesterday => 'Včeraj';

  @override
  String get today => 'Danes';

  @override
  String get caloriesLeft => 'Preostale Kalorije';

  @override
  String get everydayLogFireReflect =>
      'Vsak dan lahko zabeleži svoj 🔥, da razmisliš, ali si res dosegel, kar si želel. Tvoji požari gradijo nize, ki kažejo tvojo doslednost.';

  @override
  String get longLastingHealthEffects =>
      'Videl boš dolgotrajne učinke na svoje zdravje';

  @override
  String get ninetyPercent => '90%';

  @override
  String get usersStayConsistentMaintainWeight =>
      ' uporabnikov, ki ostanejo dosledni, ohranja svojo težo celo ';

  @override
  String get twelveMonthsLater => '12 mesecev kasneje';

  @override
  String get leaveUsReview => 'Pustite nam oceno';

  @override
  String get joinOver10000People =>
      'Pridružite se več kot 10.000\nljudem prav kot vi';

  @override
  String get applied => 'Uporabljeno';

  @override
  String get howItWorksUniqueApproach =>
      'Kako Kalorinov edinstven\npristop deluje';

  @override
  String get scan => 'Skeniraj';

  @override
  String get analyze => 'Analiziraj';

  @override
  String get track => 'Sledi';

  @override
  String get heightAndWeight => 'Višina in teža';

  @override
  String get heightWeightSubtitle =>
      'Ta informacija nam pomaga personalizirati vaše dnevne kalorične in prehranske cilje.';

  @override
  String get imperial => 'Imperialno';

  @override
  String get metric => 'Metrično';

  @override
  String get heightLabel => 'Višina';

  @override
  String get weightLabel => 'Teža';

  @override
  String get whenWereYouBorn => 'Kdaj ste bili rojeni?';

  @override
  String get birthDateSubtitle =>
      'To bo upoštevano pri izračunu vaših dnevnih prehranskih ciljev.';

  @override
  String get monthLabel => 'Mesec';

  @override
  String get dayLabel => 'Dan';

  @override
  String get yearLabel => 'Leto';

  @override
  String get january => 'Januar';

  @override
  String get february => 'Februar';

  @override
  String get march => 'Marec';

  @override
  String get april => 'April';

  @override
  String get may => 'Maj';

  @override
  String get june => 'Junij';

  @override
  String get july => 'Julij';

  @override
  String get august => 'Avgust';

  @override
  String get september => 'September';

  @override
  String get october => 'Oktober';

  @override
  String get november => 'November';

  @override
  String get december => 'December';

  @override
  String get selectYourGender => 'Izberite svoj Spol';

  @override
  String get genderSelectionInfo =>
      'Izberite spol, ki ustreza fiziologiji vašega telesa za natančno sledenje kalorij';

  @override
  String get maleGender => 'Moški';

  @override
  String get femaleGender => 'Ženska';

  @override
  String get howManyWorkoutsPerWeek => 'Koliko treningov opravite tedensko';

  @override
  String get selectBestOption => 'Izberite možnost, ki vam najbolj ustreza';

  @override
  String get noWorkouts => 'Ne treniram';

  @override
  String get occasionalWorkouts => 'Občasni treningi';

  @override
  String get severalWorkoutsWeekly => 'Več treningov tedensko';

  @override
  String get dedicatedAthlete => 'Predani športnik';

  @override
  String get whereDidYouHearAboutUs => 'Kje ste slišali za nas?';

  @override
  String get googlePlay => 'Google Play';

  @override
  String get youtube => 'YouTube';

  @override
  String get tiktok => 'TikTok';

  @override
  String get instagram => 'Instagram';

  @override
  String get influencer => 'Vplivnež';

  @override
  String get friendsOrFamily => 'Prijatelji ali Družina';

  @override
  String get other => 'Drugo';

  @override
  String get wellDoneBigStep => 'Bravo! Pravkar ste naredili\nvelik korak.';

  @override
  String get calorieTrackingPart1 => 'Ali ste vedeli, da je štetje kalorij ';

  @override
  String get scientificallyProvenMethod => 'znanstveno dokazana metoda';

  @override
  String get calorieTrackingPart2 => ' za doseganje vaših ciljev – in tudi do ';

  @override
  String get twiceFaster => 'dvakrat hitreje';

  @override
  String get calorieTrackingPart3 => '?';

  @override
  String get yourProgress => 'Vaš napredek';

  @override
  String get withKalorina => 'S Kalorino';

  @override
  String get withoutKalorina => 'Brez Kalorine';

  @override
  String get twiceMultiplier => '+2x';

  @override
  String get whatIsYourGoal => 'Kakšen je vaš cilj';

  @override
  String get selectGoalThatSuitsYou => 'Izberite cilj, ki vam najbolj ustreza';

  @override
  String get loseWeight => 'Izgubiti Težo';

  @override
  String get maintainWeight => 'Vzdrževati Težo';

  @override
  String get gainWeight => 'Pridobiti na Teži';

  @override
  String get howMuchWeightToLose => 'Koliko teže želite izgubiti?';

  @override
  String get howMuchWeightToGain => 'Koliko teže želite pridobiti?';

  @override
  String get whatIsDesiredWeight => 'Kakšna je vaša želena teža?';

  @override
  String get isRealisticGoal => 'je realen cilj.';

  @override
  String get youHaveGreatPotentialLose =>
      'Imate velik potencial za dosego svojega cilja!\nNaredimo to skupaj!';

  @override
  String get youHaveGreatPotentialGain =>
      'Izgradnja mišic zahteva predanost!\nTukaj smo, da podpremo vašo pot!';

  @override
  String get youveGotThis => 'Zmoreš to!';

  @override
  String get stayStrong => 'Ostani močan!';

  @override
  String get nineOutOfTenUsers =>
      '9 od 10 uporabnikov pravi, da\nvidijo rezultate v prvem tednu\nuporabe Kalorine';

  @override
  String get pickWeightLossSpeed => 'Izberite hitrost izgube teže';

  @override
  String get pickWeightGainSpeed => 'Izberite hitrost pridobivanja teže';

  @override
  String get theSafestOption => 'Najvarnejša možnost';

  @override
  String get balancedApproach => 'Uravnotežen pristop';

  @override
  String get aggressivePlan => 'Agresiven načrt';

  @override
  String get doYouFollowDiet => 'Ali se držite določene diete?';

  @override
  String get helpTrackCaloriesDiet =>
      'Pomagali vam bomo slediti kalorije glede na vašo dieto';

  @override
  String get classic => 'Klasična';

  @override
  String get carnivore => 'Mesojeda';

  @override
  String get keto => 'Keto';

  @override
  String get vegan => 'Veganska';

  @override
  String get vegetarian => 'Vegetarijanska';

  @override
  String get wereHereForYou => 'Tukaj smo za vas!';

  @override
  String get journeySupportMessage =>
      'Pot do vašega cilja je lahko včasih zahtevna, a mi smo tukaj, da vas podpremo na vsakem koraku. Ne boste se morali soočiti sami.';

  @override
  String get starsAcrossApps => 'Zvezdic Preko Aplikacij';

  @override
  String get testimonial1Name => 'Luka J.';

  @override
  String get testimonial1Review =>
      'Aplikacija je neverjetno natančna. Končno vem, koliko jem in se počutim veliko bolje skozi dan.';

  @override
  String get testimonial2Name => 'Marko P.';

  @override
  String get testimonial2Review =>
      'Odkar uporabljam aplikacijo, sem seznanjen s porcijami. Jem pametneje in imam več energije čez dan.';

  @override
  String get testimonial3Name => 'Jelena K.';

  @override
  String get testimonial3Review =>
      'Natančnost vnosa me je navdušila. Končno imam nadzor nad kalorijami brez stresa in štetja.';

  @override
  String get testimonial4Name => 'Emir S.';

  @override
  String get testimonial4Review =>
      'Popolno za dnevno rutino. Hitro skeniram obroke in čutim napredek že po tednu.';

  @override
  String get yes => 'Da';

  @override
  String get no => 'Ne';

  @override
  String get authenticationError => 'Authentication Error';

  @override
  String get registrationFailed => 'Registration Failed';

  @override
  String get loginFailed => 'Login Failed';

  @override
  String get networkError => 'Network Error';

  @override
  String get networkErrorDescription =>
      'Unable to connect to the server. Please check your internet connection and try again.';

  @override
  String get unexpectedError => 'Unexpected Error';

  @override
  String get unexpectedErrorDescription =>
      'Something went wrong. Please try again later.';

  @override
  String get tryAgain => 'Try Again';

  @override
  String get deleteExerciseTitle => 'Delete Exercise?';

  @override
  String get exerciseWillBePermanentlyDeleted =>
      'Exercise will be permanently deleted';

  @override
  String get failedToDeleteExercise =>
      'Failed to delete exercise. Please try again.';

  @override
  String get deleteMealTitle => 'Delete Meal?';

  @override
  String get mealWillBePermanentlyDeleted => 'Meal will be permanently deleted';

  @override
  String get howToScanProperly => 'How to scan properly';

  @override
  String get keepFoodInsideFrame => 'Keep food fully inside the frame';

  @override
  String get holdPhoneSteady => 'Hold your phone steady for a clear photo';

  @override
  String get takePictureStraight =>
      'Take the picture straight, not at an angle';
}
