// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Serbian (`sr`).
class AppLocalizationsSr extends AppLocalizations {
  AppLocalizationsSr([String locale = 'sr']) : super(locale);

  @override
  String get appTitle => 'Karolina';

  @override
  String get home => 'Početna';

  @override
  String get analytics => 'Analitika';

  @override
  String get settings => 'Postavke';

  @override
  String get calories => 'калорије';

  @override
  String get carbs => 'Угљени Хидрати';

  @override
  String get protein => 'Протеини';

  @override
  String get fats => 'Масти';

  @override
  String get setYourGoals => 'Postavi Svoje Ciljeve';

  @override
  String get autoGenerate => 'Automatska Generacija';

  @override
  String get autoGenerateDescription =>
      'Automatski generiraj ciljeve uz pomoć stručnih nutricionističkih algoritama';

  @override
  String get noFoodLogged => 'Niste učitali hranu';

  @override
  String get tapPlusToTrack =>
      'Dodirnite + da biste pratili svoj napredak i postigli svoje ciljeve';

  @override
  String get analyzing => 'Analiziram hranu...';

  @override
  String achievedGoal(int percent) {
    return 'Ostvarili ste $percent% svog cilja!';
  }

  @override
  String get database => 'Baza Podataka';

  @override
  String get gallery => 'Galerija';

  @override
  String get workout => 'Zabilježi Vježbu';

  @override
  String get scanFood => 'Skeniraj Hranu';

  @override
  String get log => 'Dnevnik';

  @override
  String get monday => 'Pon';

  @override
  String get tuesday => 'Uto';

  @override
  String get wednesday => 'Sri';

  @override
  String get thursday => 'Čet';

  @override
  String get friday => 'Pet';

  @override
  String get saturday => 'Sub';

  @override
  String get sunday => 'Ned';

  @override
  String get consistencyBuildsHealth => 'Dosljednost gradi zdravlje';

  @override
  String get healthHabitsDescription =>
      'To hit your goals and keep the weight, set a routine and make a healthy habits. Challenge your and work on it every day.';

  @override
  String get positiveHealthEffects =>
      'You\'ll see positive effects\non your health soon';

  @override
  String get healthBenefits =>
      'Reduced risk of diabetes, lower blood\npressure, improved cholesterol levels';

  @override
  String get enterReferralCode => 'Unesite referalni kod';

  @override
  String get notRequired => '(nije obavezno)';

  @override
  String get influencerCode => 'Kod Influencera';

  @override
  String get confirm => 'Potvrdi';

  @override
  String get generatingYourPlan => 'Generiramo vaš\nplan po mjeri';

  @override
  String get preparingFor => 'Preporuke za';

  @override
  String get continue_ => 'Nastavi';

  @override
  String get startTrackingToday => 'Start tracking with\nKalorina today.';

  @override
  String get photoYourMeal => 'SAMO FOTOGRAFIRAJ\nSVOJ OBROK';

  @override
  String get photoYourMealDesc =>
      'Jednostavno fotografiraj svoj obrok i automatski ćeš dobiti informacije o kalorijama';

  @override
  String get totalCalories => 'KONTROLIRAJ\nKALORIJE BEZ MUKE';

  @override
  String get controlCaloriesEffortlessly =>
      'Prati kalorije bez stresa i postižeš svoje ciljeve lakše nego ikad';

  @override
  String get achieveGoalsFaster => 'OSTVARI CILJEVE BRŽE\nNEGO IKAD';

  @override
  String get achieveGoalsDesc =>
      'Naša AI tehnologija će te voditi korak po korak do tvojih ciljeva';

  @override
  String get notificationReminder =>
      'We\'ll remind you before\nyour free trial ends.';

  @override
  String get freeTrialInfo =>
      'Probaj za €0.00 - Nema naplate ako otkažeš na\nvrijeme. Otkaži u bilo kojem trenutku.';

  @override
  String get tryForFree => 'Probaj za BESPLATNO';

  @override
  String get pricingTitle => '3 days free, then €39.99\nper year.';

  @override
  String get day1 => 'Day 1';

  @override
  String get day1Title => 'Otključaj Kalorina Pro';

  @override
  String get day1Description => 'Unlock Kalorina Pro and explore everything.';

  @override
  String get day2 => 'Day 2';

  @override
  String get day2Title => 'Prijateljski podsjetnik';

  @override
  String get day2Description =>
      'Get a friendly reminder before your trial ends.';

  @override
  String get day3 => 'Day 3';

  @override
  String get day3Title => 'Nastavi s planom';

  @override
  String get day3Description => 'Continue with your chosen plan.';

  @override
  String get yearlyPlan => 'Yearly - 3 Day Free Trial';

  @override
  String get yearlyPrice => '€2.91 /mo';

  @override
  String get monthlyPlan => 'Monthly - No Free Trial';

  @override
  String get startTrialButton => 'Start My 3-Day Trial For €0.00';

  @override
  String get cancelAnytime => 'Otkaži u bilo kojem trenutku';

  @override
  String get smarterWayTitle =>
      'Your smarter way to track\nwhat you eat starts here';

  @override
  String get noCalorieMath => 'No more calorie math';

  @override
  String get noCalorieMathDesc => 'We do the numbers, you enjoy the food.';

  @override
  String get scanTrackDone => 'Scan. Track. Done';

  @override
  String get scanTrackDoneDesc => 'Logging food takes seconds.';

  @override
  String get stayOnTopEffortlessly => 'Stay on top effortlessly';

  @override
  String get stayOnTopEffortlesslyDesc =>
      'Gentle reminders keep you consistent.';

  @override
  String get language => 'Језик';

  @override
  String get english => 'English';

  @override
  String get hrvatski => 'Hrvatski';

  @override
  String get srpski => 'Srpski';

  @override
  String get bosanski => 'Bosanski';

  @override
  String get slovenscina => 'Slovenščina';

  @override
  String get crnogorski => 'Crnogorski';

  @override
  String get makedonski => 'Македонски';

  @override
  String get bulgarski => 'Български';

  @override
  String get romana => 'Română';

  @override
  String get magyar => 'Magyar';

  @override
  String get appearance => 'Izgled';

  @override
  String get light => 'Svijetli';

  @override
  String get dark => 'Tamni';

  @override
  String get automatic => 'Automatski';

  @override
  String get createYourAccount => 'Napravi Svoj Nalog';

  @override
  String get welcomeBack => 'Dobrodošao Nazad';

  @override
  String get continueWithApple => 'Nastavi sa Apple';

  @override
  String get continueWithGoogle => 'Nastavi sa Google';

  @override
  String get wantToSignInLater => 'Želiš da se prijaviš kasnije? ';

  @override
  String get skip => 'Preskoči';

  @override
  String get byContinuingAgree =>
      'Nastavkom se slažeš sa našim\nUslovima Korišćenja i Pravilima Privatnosti';

  @override
  String get haveYouCountedCalories => 'Da li ste pre brojali\nkalorije?';

  @override
  String get triedButStopped => 'Pokušao/la sam, ali sam prestao/la.';

  @override
  String get neverSeemComplex => 'Nikad. Čini se složeno.';

  @override
  String get yesStillDoing => 'Da, i još uvek to radim.';

  @override
  String get logStreak => 'Log Streak';

  @override
  String get caloriesMoreToGo => 'Calories more to go!';

  @override
  String get todaysLunchTotals => 'Today\'s lunch totals';

  @override
  String get mealTotals => 'Meal totals';

  @override
  String get consistencyMatters =>
      'Consistency matters for achieving your goals!';

  @override
  String get continueButton => 'Continue';

  @override
  String get kalorina => 'Kalorina';

  @override
  String get exercise => 'Exercise';

  @override
  String get cardio => 'Cardio';

  @override
  String get cardioSubtitle =>
      'Log runs, cycling, HIIT, or any endurance activity';

  @override
  String get weightTraining => 'Weight Training';

  @override
  String get weightTrainingSubtitle =>
      'Track gym sessions, sets, and strength exercises';

  @override
  String get describeExercise => 'Describe Exercise';

  @override
  String get describeExerciseSubtitle => 'Let AI calculate calories burned';

  @override
  String get directInput => 'Директан Унос';

  @override
  String get directInputSubtitle => 'Type in calories burned yourself';

  @override
  String get food => 'Food';

  @override
  String get myMeals => 'Моји Оброци';

  @override
  String get myMealsSubtitle =>
      'Track gym sessions, sets, and strength exercises';

  @override
  String get myFoods => 'Моја Храна';

  @override
  String get myFoodsSubtitle => 'Let AI calculate calories burned';

  @override
  String get savedScans => 'Сачувани Скенови';

  @override
  String get savedScansSubtitle => 'Type in calories burned yourself';

  @override
  String get directInputFood => 'Direct Input';

  @override
  String get directInputFoodSubtitle => 'Type in what you ate yourself';

  @override
  String get howDoesItWork => 'How does it work?';

  @override
  String get currentStreak => 'Current streak';

  @override
  String get longestStreak => 'Longest streak';

  @override
  String get day => 'day';

  @override
  String get days => 'days';

  @override
  String get successfulDay => 'Successful day';

  @override
  String get failedDay => 'Failed day';

  @override
  String get undo => 'Undo';

  @override
  String get error => 'Error';

  @override
  String get success => 'Success';

  @override
  String get info => 'Info';

  @override
  String get failedToCreateStreak => 'Failed to create streak';

  @override
  String get streakUndoneFor => 'Streak undone for';

  @override
  String get noStreakToUndoFor => 'No streak to undo for';

  @override
  String get howDoesItWorkTitle => 'How does it work?';

  @override
  String get howDoesItWorkDescription =>
      'Every day, you can log your fire to reflect on whether you felt like you truly achieved what you wanted.';

  @override
  String get successfulDescription =>
      'Successful → You reached your daily goal or feel satisfied with your progress.';

  @override
  String get failedDescription =>
      'Failed → You didn\'t meet your goal or the day didn\'t go as planned.';

  @override
  String get streakExplanation =>
      'Your fires build streaks that show your consistency. The longer you log honestly, the clearer you\'ll see your real progress.';

  @override
  String get logExercise => 'Пријави вежбу';

  @override
  String get weightTrainingTab => 'Тренинг са теговима';

  @override
  String get describeTab => 'Опиши';

  @override
  String get directInputTab => 'Директан унос';

  @override
  String get low => 'Низак';

  @override
  String get medium => 'Средњи';

  @override
  String get high => 'Висок';

  @override
  String get intensity => 'Интензитет';

  @override
  String get duration => 'Трајање';

  @override
  String get fifteenMin => '15 мин';

  @override
  String get thirtyMin => '30 мин';

  @override
  String get fortyFiveMin => '45 мин';

  @override
  String get sixtyMin => '60 мин';

  @override
  String get logging => 'Пријављивање...';

  @override
  String get add => 'Додај';

  @override
  String get aiPowered => 'Покреће ИА';

  @override
  String get explainWorkoutPlaceholder => 'Објасни трајање вежбе, напор, итд.';

  @override
  String get workoutExample =>
      'Пример: \"Тренинг горњег дела тела, 45 мин, средњи напор\"';

  @override
  String get estimating => 'Процена...';

  @override
  String get aiEstimate => 'ИА процена';

  @override
  String get whyThisEstimate => 'Зашто ова процена';

  @override
  String get typeCaloriesBurned => 'Унеси спаљене калорије сам';

  @override
  String get zeroPlaceholder => '0';

  @override
  String get nearSprintingDescription => 'Готово спринт, тешко одржати дуго';

  @override
  String get steadyRunDescription => 'Стабилно трчање, подношљив напор';

  @override
  String get briskWalkDescription => 'Брза шетња, удобно дисање';

  @override
  String get heavyWeightsDescription =>
      'Тешки тегови, близу максималног напора';

  @override
  String get moderateWeightsDescription => 'Умерени тегови, знојење';

  @override
  String get lightWeightsDescription => 'Лаки тегови, без знојења';

  @override
  String get logFood => 'Забележи Храну';

  @override
  String get all => 'Све';

  @override
  String get searchMeals => 'Претражи оброке...';

  @override
  String get searchFoods => 'Претражи храну...';

  @override
  String get searchScannedMeals => 'Претражи скениране оброке...';

  @override
  String get chickenBr => 'Пиле br';

  @override
  String get suggestions => 'Предлози';

  @override
  String get noSuggestionsAvailable => 'Нема доступних предлога';

  @override
  String get noMealsSavedYet => 'Још нема сачуваних оброка';

  @override
  String get noFoodsCreatedYet => 'Још нема створене хране';

  @override
  String get createFood => 'Створи Храну';

  @override
  String get yourSavedScansWillAppearHere =>
      'Ваши сачувани скенови ће се појавити овде';

  @override
  String get savedScansContentComingSoon => 'Садржај сачуваних скенова ускоро';

  @override
  String get editName => 'Уреди Име';

  @override
  String get caloriesLabel => 'Калорије';

  @override
  String get caloriesPlaceholder => '512';

  @override
  String get ingredients => 'Састојци';

  @override
  String get addMore => 'Додај Више';

  @override
  String get amount => 'Количина';

  @override
  String get saveFood => 'Сачувај Храну';

  @override
  String get createAMeal => 'Створи Оброк';

  @override
  String get enterAmount => 'Унеси Количину';

  @override
  String get enterAmountPlaceholder => 'Унеси количину';

  @override
  String get cancel => 'Откажи';

  @override
  String get save => 'Сачувај';

  @override
  String get name => 'Име *';

  @override
  String get enterIngredientName => 'Унеси име састојка';

  @override
  String get quantityUnit => 'Количина и Јединица';

  @override
  String get amountPlaceholder => 'Количина';

  @override
  String get unitPlaceholder => 'Јединица (г, шоља, кашика)';

  @override
  String get nutritionOptional => 'Исхрана (Опционо)';

  @override
  String get caloriesPlaceholder2 => 'Калорије';

  @override
  String get proteinG => 'Протеини (г)';

  @override
  String get carbsG => 'Угљени Хидрати (г)';

  @override
  String get fatG => 'Масти (г)';

  @override
  String get editIngredient => 'Уреди Састојак';

  @override
  String get addIngredient => 'Додај Састојак';

  @override
  String get scannedMeal => 'Скениран Оброк';

  @override
  String get setName => 'Постави Име';

  @override
  String get personalInformation => 'Личне Информације';

  @override
  String get weight => 'Тежина';

  @override
  String get height => 'Висина';

  @override
  String get age => 'Доб';

  @override
  String get gender => 'Пол';

  @override
  String get dailyStepsGoal => 'Дневни циљ корака';

  @override
  String get addBurnedCaloriesToGoal => 'Додај Спаљене Калорије у Циљ';

  @override
  String get account => 'Налог';

  @override
  String get manageYourProfileAndAccountSettings =>
      'Управљај својим профилом и подешавањима налога';

  @override
  String get healthTracking => 'Праћење Здравља';

  @override
  String get viewYourHealthConsistencyAndProgress =>
      'Погледај своју здравствену доследност и напредак';

  @override
  String get notifications => 'Обавештења';

  @override
  String get configureYourNotificationPreferences =>
      'Конфигуриши своје поставке обавештења';

  @override
  String get about => 'О Апликацији';

  @override
  String get appVersionAndInformation => 'Верзија апликације и информације';

  @override
  String get enterYourName => 'Унеси своје име';

  @override
  String get selectGender => 'Одабери Пол';

  @override
  String get male => 'Мушки';

  @override
  String get female => 'Женски';

  @override
  String get years => 'година';

  @override
  String get steps => 'корака';

  @override
  String get progress => 'Напредак';

  @override
  String get myWeight => 'Моја Тежина';

  @override
  String get logWeight => 'Пријави Тежину';

  @override
  String get targetWeight => 'Циљна Тежина';

  @override
  String get update => 'Ажурирај';

  @override
  String get toTargetWeight => 'До циљне тежине';

  @override
  String get weightGoalProgress => 'Напредак Циља Тежине';

  @override
  String get thirtyDays => '30 Дана';

  @override
  String get ninetyDays => '90 Дана';

  @override
  String get sixMonths => '6 Месеци';

  @override
  String get oneYear => '1 Година';

  @override
  String get allTime => 'Све Време';

  @override
  String get start => 'Почетак';

  @override
  String get now => 'Сада';

  @override
  String get avgDailyProgress => 'Просечни дневни напредак';

  @override
  String get avgDailyLost => 'Просечно дневно изгубљено';

  @override
  String get avgDailyGained => 'Просечно дневно добијено';

  @override
  String get addProgressPhoto => 'Додај Фотографију Напретка';

  @override
  String get camera => 'Камера';

  @override
  String get progressPhotos => 'Фотографије Напретка';

  @override
  String get seeProgress => 'Види напредак';

  @override
  String get uploadPhoto => 'Учитај Фотографију';

  @override
  String get upload => 'Учитај';

  @override
  String get stepsToday => 'Кораци Данас';

  @override
  String get tapToEnableHealthPermissions =>
      'Додирни за омогућавање здравствених дозвола';

  @override
  String get addBurnedCaloriesToDailyGoal =>
      'Додај спаљене калорије у дневни циљ';

  @override
  String get caloriesBurned => 'Спаљене Калорије';

  @override
  String get kg => 'кг';

  @override
  String get sinceLastWeighIn => 'од последњег мерења';

  @override
  String get kgPerDay => 'кг/дан';

  @override
  String get kgToGo => 'кг до циља';

  @override
  String get greatJob => 'Одлично';

  @override
  String get youGained => 'Добио си';

  @override
  String get weighInDue => 'Мерење потребно';

  @override
  String nextWeighIn(Object days) {
    return 'Следеће мерење: $daysд';
  }

  @override
  String get enterUsername => 'Унесите корисничко име';

  @override
  String get birthday => 'Рођендан';

  @override
  String get personalDetails => 'Лични подаци';

  @override
  String get rolloverLeftOverCalories =>
      'Преноси до 200 преосталих калорија од јуче';

  @override
  String get addBurnedCalories => 'Додај спаљене калорије';

  @override
  String get inviteFriends => 'Позови пријатеље';

  @override
  String get adjustMacronutrients => 'Прилагоди макронутријенте';

  @override
  String get support => 'Подршка';

  @override
  String get privacyPolicy => 'Политика приватности';

  @override
  String get termsAndConditions => 'Услови и одредбе';

  @override
  String get deleteAccount => 'Обриши налог';

  @override
  String get logout => 'Одјава';

  @override
  String get deleteAccountTitle => 'Обрисати налог?';

  @override
  String get accountWillBePermanentlyDeleted => 'Налог ће бити трајно обрисан';

  @override
  String get logoutTitle => 'Одјавити се?';

  @override
  String get areYouSureYouWantToLogOut =>
      'Да ли сте сигурни да се желите одјавити?';

  @override
  String get recentlyUploaded => 'Недавно преузето';

  @override
  String get cannotLogFutureStreak => 'Не можете евидентирати будуће датуме';

  @override
  String get cannotLogFutureStreakDescription =>
      'Можете евидентирати низове само за данас и прошле датуме. Будући датуми ће се откључати како буду долазили!';

  @override
  String dayStreak(int count) {
    return 'Дан $count Низ';
  }

  @override
  String get keepGoing => 'Настави!';

  @override
  String get ok => 'У реду';

  @override
  String get whatWouldYouLikeToAchieve => 'Шта бисте желели да постигнете?';

  @override
  String get stayMotivatedAndDisciplined => 'Остати мотивисан и дисциплинован';

  @override
  String get feelBetterAboutYourBody => 'Осећати се боље у вези свог тела';

  @override
  String get improveHealthLongTerm => 'Дугорочно побољшати здравље';

  @override
  String get increaseMoodAndEnergy => 'Повећати расположење и енергију';

  @override
  String get youHaveGreatPotential =>
      'Имаш велики потенцијал да оствариш свој циљ';

  @override
  String get yourJourneyToBetterHealth =>
      'Твој пут ка бољем здрављу почиње сада';

  @override
  String get youTookFirstStepToHealthier =>
      'Направио си први корак ка здравијој верзији себе';

  @override
  String get trackYourFoodAndExercise => 'Прати своју храну и вежбање';

  @override
  String get focusOnNutrientDenseFoods =>
      'Фокусирај се на храну богату хранљивим материјама';

  @override
  String get maintainYourHealthyHabits => 'Одржавај своје здраве навике';

  @override
  String get balanceCarbsProteinAndFats =>
      'Балансирај угљене хидрате, протеине и масти';

  @override
  String get stickToYourPersonalizedPlan =>
      'Придржавај се свог персонализованог плана';

  @override
  String get focusOnWholeUnprocessedFoods =>
      'Фокусирај се на целовиту, необрађену храну';

  @override
  String get followYourPersonalizedMealPlan =>
      'Следи свој персонализовани план оброка';

  @override
  String get focusOnPortionControlAndNutrition =>
      'Фокусирај се на контролу порција и исхрану';

  @override
  String get followYourPersonalizedPlan => 'Следи свој персонализовани план';

  @override
  String get stayConsistentSeeRealResults =>
      'Буди доследан, види праве резултате';

  @override
  String get enableNotificationsForBetterResults =>
      'Омогући обавештења за боље резултате';

  @override
  String get recommended => '(Препоручено)';

  @override
  String get kalorinaHelpsYouKeepTrack =>
      'Каролина ти помаже да пратиш — Примај дневне подсетнике';

  @override
  String get dontAllow => 'Не дозволи';

  @override
  String get allow => 'Дозволи';

  @override
  String get countBurnedCaloriesTowardsGoal =>
      'Рачунати спаљене калорије ка дневном циљу?';

  @override
  String get todaysGoal => 'Данашњи циљ:';

  @override
  String get stepsLabel => 'Кораци:';

  @override
  String get transferExtraCaloriesToNextDay =>
      'Пребаци додатне калорије на следећи дан?';

  @override
  String get yesterday => 'Јуче';

  @override
  String get today => 'Данас';

  @override
  String get caloriesLeft => 'Преостале Калорије';

  @override
  String get everydayLogFireReflect =>
      'Сваког дана можеш забележити своју 🔥 како би размислио да ли си заиста постигао оно што си желео. Твоје ватре граде серије које показују твоју доследност.';

  @override
  String get longLastingHealthEffects =>
      'Видећеш дуготрајне ефекте на своје здравље';

  @override
  String get ninetyPercent => '90%';

  @override
  String get usersStayConsistentMaintainWeight =>
      ' корисника који остају доследни одржавају своју тежину чак ';

  @override
  String get twelveMonthsLater => '12 месеци касније';

  @override
  String get leaveUsReview => 'Остави нам рецензију';

  @override
  String get joinOver10000People =>
      'Придружи се више од 10.000\nљуди баш попут тебе';

  @override
  String get applied => 'Примењено';

  @override
  String get howItWorksUniqueApproach =>
      'Како Каролинин јединствени\nприступ функционише';

  @override
  String get scan => 'Скенирај';

  @override
  String get analyze => 'Анализирај';

  @override
  String get track => 'Прати';

  @override
  String get heightAndWeight => 'Висина и тежина';

  @override
  String get heightWeightSubtitle =>
      'Ова информација нам помаже да персонализујемо ваше дневне калоријске и нутритивне циљеве.';

  @override
  String get imperial => 'Империјал';

  @override
  String get metric => 'Метрички';

  @override
  String get heightLabel => 'Висина';

  @override
  String get weightLabel => 'Тежина';

  @override
  String get whenWereYouBorn => 'Када сте рођени?';

  @override
  String get birthDateSubtitle =>
      'Ово ће бити узето у обзир приликом израчунавања ваших дневних нутритивних циљева.';

  @override
  String get monthLabel => 'Месец';

  @override
  String get dayLabel => 'Дан';

  @override
  String get yearLabel => 'Година';

  @override
  String get january => 'Јануар';

  @override
  String get february => 'Фебруар';

  @override
  String get march => 'Март';

  @override
  String get april => 'Април';

  @override
  String get may => 'Мај';

  @override
  String get june => 'Јун';

  @override
  String get july => 'Јул';

  @override
  String get august => 'Август';

  @override
  String get september => 'Септембар';

  @override
  String get october => 'Октобар';

  @override
  String get november => 'Новембар';

  @override
  String get december => 'Децембар';

  @override
  String get selectYourGender => 'Одабери свој Пол';

  @override
  String get genderSelectionInfo =>
      'Одаберите пол који одговара физиологији вашег тела за прецизно праћење калорија';

  @override
  String get maleGender => 'Мушкарац';

  @override
  String get femaleGender => 'Жена';

  @override
  String get howManyWorkoutsPerWeek => 'Колико тренинга радиш недељно';

  @override
  String get selectBestOption => 'Одаберите опцију која вам највише одговара';

  @override
  String get noWorkouts => 'Не тренирам';

  @override
  String get occasionalWorkouts => 'Тренинзи с времена на време';

  @override
  String get severalWorkoutsWeekly => 'Неколико тренинга недељно';

  @override
  String get dedicatedAthlete => 'Предани спортиста';

  @override
  String get whereDidYouHearAboutUs => 'Где сте чули за нас?';

  @override
  String get googlePlay => 'Google Play';

  @override
  String get youtube => 'YouTube';

  @override
  String get tiktok => 'TikTok';

  @override
  String get instagram => 'Instagram';

  @override
  String get influencer => 'Инфлуенсер';

  @override
  String get friendsOrFamily => 'Пријатељи или Породица';

  @override
  String get other => 'Остало';

  @override
  String get wellDoneBigStep => 'Браво! Управо сте направили\nвелик корак.';

  @override
  String get calorieTrackingPart1 => 'Јесте ли знали да је праћење калорија ';

  @override
  String get scientificallyProvenMethod => 'научно доказана метода';

  @override
  String get calorieTrackingPart2 => ' остваривања ваших циљева – и то и до ';

  @override
  String get twiceFaster => 'двоструко брже';

  @override
  String get calorieTrackingPart3 => '?';

  @override
  String get yourProgress => 'Ваш напредак';

  @override
  String get withKalorina => 'Са Каролином';

  @override
  String get withoutKalorina => 'Без Каролине';

  @override
  String get twiceMultiplier => '+2x';

  @override
  String get whatIsYourGoal => 'Који је твој циљ';

  @override
  String get selectGoalThatSuitsYou =>
      'Одаберите циљ који вам највише одговара';

  @override
  String get loseWeight => 'Смршати';

  @override
  String get maintainWeight => 'Одржавати Тежину';

  @override
  String get gainWeight => 'Добити на Тежини';

  @override
  String get howMuchWeightToLose => 'Колико тежине желите изгубити?';

  @override
  String get howMuchWeightToGain => 'Колико тежине желите добити?';

  @override
  String get whatIsDesiredWeight => 'Која је ваша жељена тежина?';

  @override
  String get isRealisticGoal => 'је реалан циљ.';

  @override
  String get youHaveGreatPotentialLose =>
      'Имаш велики потенцијал постићи свој циљ!\nХајде да то остваримо заједно!';

  @override
  String get youHaveGreatPotentialGain =>
      'Изградња мишића захтева предање!\nОвде смо да подржимо твој пут!';

  @override
  String get youveGotThis => 'Можеш то!';

  @override
  String get stayStrong => 'Буди јак!';

  @override
  String get nineOutOfTenUsers =>
      '9 од 10 корисника каже да\nвиде резултате у првој недељи\nкоришћења Каролине';

  @override
  String get pickWeightLossSpeed => 'Изабери брзину губитка тежине';

  @override
  String get pickWeightGainSpeed => 'Изабери брзину добијања тежине';

  @override
  String get theSafestOption => 'Најсигурнија опција';

  @override
  String get balancedApproach => 'Балансиран приступ';

  @override
  String get aggressivePlan => 'Агресиван план';

  @override
  String get doYouFollowDiet => 'Придржавате ли се одређене дијете?';

  @override
  String get helpTrackCaloriesDiet =>
      'Помоћи ћемо вам пратити калорије према вашем начину исхране';

  @override
  String get classic => 'Класична';

  @override
  String get carnivore => 'Carnivore';

  @override
  String get keto => 'Keto';

  @override
  String get vegan => 'Vegan';

  @override
  String get vegetarian => 'Vegetarian';

  @override
  String get wereHereForYou => 'Ту смо за тебе!';

  @override
  String get journeySupportMessage =>
      'Пут до твог циља може бити изазован с времена на време, али ми смо ту да те подржимо на сваком кораку. Нећеш то морати суочити сам.';

  @override
  String get starsAcrossApps => 'Звездица Преко Апликација';

  @override
  String get testimonial1Name => 'Лука Ј.';

  @override
  String get testimonial1Review =>
      'Апликација је невероватно прецизна. Коначно знам колико једем и осећам се пуно боље кроз дан.';

  @override
  String get testimonial2Name => 'Марко П.';

  @override
  String get testimonial2Review =>
      'Од кад користим апликацију, свестан сам порција. Једем паметније и имам више енергије током дана.';

  @override
  String get testimonial3Name => 'Јелена К.';

  @override
  String get testimonial3Review =>
      'Прецизност уноса ме одушевила. Напокон имам контролу над калоријама без стреса и бројања.';

  @override
  String get testimonial4Name => 'Емир С.';

  @override
  String get testimonial4Review =>
      'Савршено за свакодневну рутину. Брзо скенирам оброке и осећам напредак већ након седмице.';
}
