// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Italian (`it`).
class AppLocalizationsIt extends AppLocalizations {
  AppLocalizationsIt([String locale = 'it']) : super(locale);

  @override
  String get appTitle => 'Karolina';

  @override
  String get home => 'Home';

  @override
  String get analytics => 'Analisi';

  @override
  String get settings => 'Impostazioni';

  @override
  String get calories => 'Calorie';

  @override
  String get carbs => 'Carboidrati';

  @override
  String get protein => 'Proteine';

  @override
  String get fats => 'Grassi';

  @override
  String get setYourGoals => 'Imposta I Tuoi Obiettivi';

  @override
  String get autoGenerate => 'Generazione Automatica';

  @override
  String get autoGenerateDescription =>
      'Genera automaticamente obiettivi utilizzando algoritmi nutrizionali esperti';

  @override
  String get noFoodLogged => 'Nessun cibo registrato';

  @override
  String get tapPlusToTrack =>
      'Tocca + per monitorare i tuoi progressi e raggiungere i tuoi obiettivi';

  @override
  String get analyzing => 'Analizzando cibo...';

  @override
  String achievedGoal(int percent) {
    return 'Hai raggiunto il $percent% del tuo obiettivo!';
  }

  @override
  String get database => 'Database';

  @override
  String get gallery => 'Galleria';

  @override
  String get workout => 'Registra Allenamento';

  @override
  String get scanFood => 'Scansiona Cibo';

  @override
  String get log => 'Registro';

  @override
  String get monday => 'Lun';

  @override
  String get tuesday => 'Mar';

  @override
  String get wednesday => 'Mer';

  @override
  String get thursday => 'Gio';

  @override
  String get friday => 'Ven';

  @override
  String get saturday => 'Sab';

  @override
  String get sunday => 'Dom';

  @override
  String get consistencyBuildsHealth => 'La costanza costruisce la salute';

  @override
  String get healthHabitsDescription =>
      'Per raggiungere i tuoi obiettivi e mantenere il peso, stabilisci una routine e crea abitudini sane. Sfidati e lavora su questo ogni giorno.';

  @override
  String get positiveHealthEffects =>
      'Vedrai effetti positivi\nsulla tua salute presto';

  @override
  String get healthBenefits =>
      'Rischio ridotto di diabete, pressione sanguigna\npiù bassa, livelli di colesterolo migliorati';

  @override
  String get enterReferralCode => 'Inserisci codice di riferimento';

  @override
  String get notRequired => '(non richiesto)';

  @override
  String get influencerCode => 'Codice Influencer';

  @override
  String get confirm => 'Conferma';

  @override
  String get generatingYourPlan => 'Generando il tuo\npiano personalizzato';

  @override
  String get preparingFor => 'Preparazione per';

  @override
  String get continue_ => 'Continua';

  @override
  String get startTrackingToday => 'Inizia a tracciare con\nKalorina oggi.';

  @override
  String get photoYourMeal => 'FOTOGRAFA SEMPLICEMENTE\nIL TUO PASTO';

  @override
  String get photoYourMealDesc =>
      'Scatta semplicemente una foto del tuo pasto e ottieni automaticamente informazioni caloriche';

  @override
  String get totalCalories => 'CONTROLLA LE\nCALORIE SENZA SFORZO';

  @override
  String get controlCaloriesEffortlessly =>
      'Traccia le calorie senza stress e raggiungi i tuoi obiettivi più facilmente che mai';

  @override
  String get achieveGoalsFaster =>
      'RAGGIUNGI GLI OBIETTIVI PIÙ VELOCEMENTE\nCHE MAI';

  @override
  String get achieveGoalsDesc =>
      'La nostra tecnologia AI ti guiderà passo dopo passo verso i tuoi obiettivi';

  @override
  String get notificationReminder =>
      'Ti ricorderemo prima che\nla tua prova gratuita finisca.';

  @override
  String get freeTrialInfo =>
      'Prova per €0.00 - Nessun addebito se annulli in\ntempo. Annulla in qualsiasi momento.';

  @override
  String get tryForFree => 'Prova GRATIS';

  @override
  String get pricingTitle => '3 days free, then €39.99\nper year.';

  @override
  String get day1 => 'Day 1';

  @override
  String get day1Title => 'Unlock Kalorina Pro';

  @override
  String get day1Description => 'Unlock Kalorina Pro and explore everything.';

  @override
  String get day2 => 'Day 2';

  @override
  String get day2Title => 'Friendly Reminder';

  @override
  String get day2Description =>
      'Get a friendly reminder before your trial ends.';

  @override
  String get day3 => 'Day 3';

  @override
  String get day3Title => 'Continue with Plan';

  @override
  String get day3Description => 'Continue with your chosen plan.';

  @override
  String get yearlyPlan => 'Yearly - 3 Day Free Trial';

  @override
  String get yearlyPrice => '€2.91 /mo';

  @override
  String get monthlyPlan => 'Monthly - No Free Trial';

  @override
  String get startTrialButton => 'Start My 3-Day Trial For €0.00';

  @override
  String get cancelAnytime => 'Cancel at any time';

  @override
  String get smarterWayTitle =>
      'Your smarter way to track\nwhat you eat starts here';

  @override
  String get noCalorieMath => 'No more calorie math';

  @override
  String get noCalorieMathDesc => 'We do the numbers, you enjoy the food.';

  @override
  String get scanTrackDone => 'Scan. Track. Done';

  @override
  String get scanTrackDoneDesc => 'Logging food takes seconds.';

  @override
  String get stayOnTopEffortlessly => 'Stay on top effortlessly';

  @override
  String get stayOnTopEffortlesslyDesc =>
      'Gentle reminders keep you consistent.';

  @override
  String get language => 'Language';

  @override
  String get english => 'English';

  @override
  String get hrvatski => 'Hrvatski';

  @override
  String get srpski => 'Srpski';

  @override
  String get bosanski => 'Bosanski';

  @override
  String get slovenscina => 'Slovenščina';

  @override
  String get crnogorski => 'Crnogorski';

  @override
  String get makedonski => 'Македонски';

  @override
  String get bulgarski => 'Български';

  @override
  String get romana => 'Română';

  @override
  String get magyar => 'Magyar';

  @override
  String get appearance => 'Appearance';

  @override
  String get light => 'Light';

  @override
  String get dark => 'Dark';

  @override
  String get automatic => 'Automatic';

  @override
  String get createYourAccount => 'Crea il tuo account';

  @override
  String get welcomeBack => 'Bentornato';

  @override
  String get continueWithApple => 'Continua con Apple';

  @override
  String get continueWithGoogle => 'Continua con Google';

  @override
  String get wantToSignInLater => 'Vuoi accedere più tardi? ';

  @override
  String get skip => 'Salta';

  @override
  String get byContinuingAgree =>
      'Continuando accetti i nostri\nTermini di servizio e Informativa sulla privacy';

  @override
  String get haveYouCountedCalories => 'Have you counted\ncalories before?';

  @override
  String get triedButStopped => 'I\'ve tried but stopped.';

  @override
  String get neverSeemComplex => 'Never. It seems complex.';

  @override
  String get yesStillDoing => 'Yes, and I\'m still doing it.';
}
